= Fazit und Ausblick

Die vorliegende Arbeit hat untersucht, wie KI-Textgenerierung die Wissensarbeit bei SAP verändert und welche Chancen und Risiken sich daraus ergeben. Ausgehend von einer systematischen Literaturanalyse in Kapitel 4 wurden theoretische Befunde zu Veränderungen in Arbeitsprozessen, Kompetenzprofilen sowie Chancen und Risiken erarbeitet. In Kapitel 5 wurden diese Befunde anhand leitfadengestützter Experteninterviews mit vier Wissensarbeitenden bei SAP empirisch überprüft, diskutiert und durch Handlungsempfehlungen für die Organisation ergänzt. Das abschließende Kapitel fasst die zentralen Ergebnisse der Arbeit zusammen und gibt einen Ausblick auf offene Fragen und mögliche Anknüpfungspunkte für weiterführende Forschung.

== Zusammenfassung der Ergebnisse

Die Arbeit zeigt, dass KI-Textgenerierung die Wissensarbeit nicht durch eine vollständige Ablösung menschlicher Tätigkeiten verändert, sondern durch eine mehrstufige Verschiebung von Aufgabenschwerpunkten. Routineorientierte Tätigkeiten wie Texterstellung, Dokumentation und Informationsrecherche werden zunehmend durch Large Language Models unterstützt oder übernommen, während Wissensarbeitende stärker in steuernde, überwachende und qualitätssichernde Rollen wechseln. Dieser Befund aus der Literatur wird durch alle vier befragten Interviewpartner bestätigt, die übereinstimmend berichten, dass KI für sie als Assistenzsystem fungiert, das ihre Arbeit erweitert, aber nicht ersetzt.

Gleichzeitig bringt dieser Wandel veränderte Kompetenzanforderungen mit sich. KI-Kompetenz und kritisches Denken werden zur neuen Grundvoraussetzung, da generierte Inhalte stets bewertet und hinterfragt werden müssen. Implizites Erfahrungswissen gewinnt an Wert, weil Large Language Models auf explizitem Textwissen basieren und situatives Urteilsvermögen sowie kontextabhängige Entscheidungen nicht replizieren können. Darüber hinaus erweist sich Datenschutz- und Sicherheitskompetenz als wachsende Querschnittsanforderung, die in den Interviews besonders deutlich als drängend beschrieben wird. Die Interviews ergänzen die Literatur dabei an zwei Stellen, die bislang weniger prominent diskutiert werden, nämlich die strukturelle Sichtbarkeitslücke bei Datenschutzvorgaben in Tool-Oberflächen sowie das Verlernrisiko, das sich besonders in technischen Tätigkeitsfeldern zeigt und durch intensive KI-Nutzung schleichend entstehen kann.

Die Chancen des KI-Einsatzes liegen vor allem in der Entlastung von Routinetätigkeiten, der Aufwertung strategisch-inhaltlicher Arbeit und der Beschleunigung analytischer Prozesse. Dem gegenüber stehen Risiken durch unkritische KI-Nutzung, den Wegfall klassischer Lernpfade für weniger erfahrene Mitarbeitende, eine wachsende Qualifikationslücke zwischen KI-affinen und KI-ablehnenden Beschäftigten sowie eine bislang wenig beachtete Frage der Chancengerechtigkeit durch ungleiche KI-Nutzungsbudgets. Die abgeleiteten Handlungsempfehlungen adressieren diese Herausforderungen auf organisationaler Ebene und betonen, dass SAP den strukturellen Rahmen für einen verantwortungsvollen KI-Einsatz aktiv gestalten muss, anstatt ihn der individuellen Initiative der Mitarbeitenden zu überlassen.

Zusammenfassend lässt sich festhalten, dass die Forschungsfrage, wie KI-Textgenerierung Arbeitsprozesse und Kompetenzprofile in der Wissensarbeit bei SAP verändert sowie welche Chancen und Risiken sich daraus ergeben, durch die Kombination aus Literaturanalyse und Experteninterviews differenziert beantwortet werden konnte. Die Ergebnisse sind dabei nicht als abgeschlossener Befund zu verstehen, sondern als Momentaufnahme eines sich dynamisch entwickelnden Feldes.

== Ausblick

Die vorliegende Arbeit öffnet mehrere Anknüpfungspunkte für weiterführende Forschung. Erstens beschränkt sich die Untersuchung auf einen einzelnen Unternehmensfall mit vier Interviewpartnerinnen und Interviewpartnern, von denen drei aus derselben Organisationseinheit stammen. Eine Mehrfallstudie, die verschiedene Unternehmen, Branchen oder Unternehmensgrößen einbezieht, könnte prüfen, ob die identifizierten Muster übertragbar sind oder ob SAP als Technologieunternehmen mit fortgeschrittener KI-Adoption einen Sonderfall darstellt.

Zweitens wäre eine Längsschnittstudie aufschlussreich, die dieselben oder vergleichbare Wissensarbeitende über einen längeren Zeitraum begleitet. Die Frage, ob das beschriebene Verlernrisiko tatsächlich eintritt und in welchem Umfang sich Kompetenzprofile langfristig verschieben, lässt sich mit einem einmaligen Querschnittdesign nicht abschließend beantworten.

Drittens wurde in der Arbeit bewusst auf die Perspektive von Berufsanfängerinnen und Berufsanfängern verzichtet, da die Untersuchungseinheit auf aktive LLM-Nutzende fokussiert war. Gerade für diese Gruppe ist jedoch die Frage besonders relevant, ob der Wegfall klassischer Lernpfade durch KI-gestützte Routineübernahme langfristig den Aufbau impliziten Erfahrungswissens beeinträchtigt. Hier besteht erheblicher Forschungsbedarf, der über die vorliegende Arbeit hinausgeht.

Schließlich entwickelt sich das Forschungsfeld der generativen KI außergewöhnlich schnell weiter. Neue Modellgenerationen, agentenbasierte Systeme und eine zunehmende Integration in Unternehmensprozesse werden die in dieser Arbeit beschriebenen Veränderungen voraussichtlich weiter verstärken und neue Fragen aufwerfen, die zum Zeitpunkt der Untersuchung noch nicht absehbar waren. Eine kontinuierliche wissenschaftliche Begleitung dieser Entwicklung bleibt daher notwendig.
