= Theoretische Grundlagen

Der Einsatz generativer Künstlicher Intelligenz in der Arbeitswelt hat in den vergangenen Jahren erheblich an Dynamik gewonnen. Insbesondere Large Language Models erschließen zunehmend Aufgabenbereiche, die bislang überwiegend menschlicher Expertise vorbehalten waren, wie etwa komplexes Sprachverständnis, kreative Textgenerierung und analytische Problemlösung (vgl. @DellAcqua2026[S. 1]; @Eloundou2023GPTsAreGPTs[S. 1-3]). Damit stellt diese Technologie nicht nur einen weiteren Digitalisierungsschritt dar, sondern greift unmittelbar in die Kernprozesse wissensintensiver Arbeit ein.



Um die Auswirkungen dieser Entwicklung auf die Wissensarbeit bei SAP im weiteren Verlauf der Arbeit systematisch analysieren zu können, werden in diesem Kapitel zunächst die theoretischen Grundlagen erarbeitet, auf denen die nachfolgende Untersuchung aufbaut. Abschnitt 2.1 definiert zunächst den Begriff der Wissensarbeit und beschreibt den durch LLMs ausgelösten Wandel. Abschnitt 2.2 erläutert anschließend die technische Funktionsweise von Large Language Models sowie deren Einsatzmöglichkeiten in der Wissensarbeit, wobei die Betrachtung bewusst auf die Textgenerierung beschränkt bleibt, da diese im unternehmerischen Kontext die dominierende Anwendungsform darstellt.

Zur begrifflichen Klarheit sei vorab darauf hingewiesen, dass generative KI der übergeordnete Technologiebereich ist, der neben Textgenerierung auch Anwendungen wie Bild-, Audio- und Videogenerierung umfasst. Large Language Models sind die konkrete Technologieklasse innerhalb dieses Bereichs, die auf Sprachverarbeitung spezialisiert ist und Textgenerierung ermöglicht. KI-Textgenerierung beschreibt entsprechend die Anwendung dieser Modelle. In der vorliegenden Arbeit werden diese Begriffe daher nicht synonym verwendet, sondern beziehen sich jeweils auf diese spezifischen Bedeutungsebenen.

== Wissensarbeit im digitalen Wandel

Der Begriff des Wissensarbeitenden wurde durch Peter Drucker geprägt (vgl. @drucker1999knowledge). Unter Wissensarbeit wird dabei eine Form spezialisierter Arbeit verstanden, deren zentrales Kapital Wissen darstellt (vgl. @Woodruff2024[S. 2]). Dementsprechend wird Wissen in Unternehmen häufig als eine der wichtigsten Ressourcen betrachtet und kann einen wesentlichen Wettbewerbsvorteil darstellen (vgl. @Kusterer2008[S. 1]). Wissensarbeit ist dadurch gekennzeichnet, dass sie ein hohes Maß an formaler Ausbildung sowie die Fähigkeit erfordert, theoretisches und analytisches Wissen anzuwenden. Hinzu kommt die Bereitschaft zum kontinuierlichen Lernen als wesentliches Merkmal (vgl. @Drucker1994AgeOfSocialTransformation). Des Weiteren wird Wissen im ressourcenbasierten Ansatz als immaterielle Ressource verstanden, die aufgrund ihres Wertes, ihrer Seltenheit sowie ihrer eingeschränkten Imitier- und Substituierbarkeit zur Schaffung eines nachhaltigen Wettbewerbsvorteils beitragen kann (vgl. @Kusterer2008[S. 13]).
Die zunehmende Digitalisierung verändert die Rahmenbedingungen der Arbeit grundlegend und beeinflusst damit auch die Wissensarbeit (vgl. @Trenerry2021[S. 1–2]). Insbesondere digitale Technologien wie künstliche Intelligenz, Automatisierung, Cloud Computing und das Internet of Things verändern die Art und Weise, wie Arbeit organisiert und ausgeführt wird (vgl. @Trenerry2021[S. 1–2]). Als spezifische Gruppe von Arbeitnehmenden, deren zentrale Ressource Wissen ist (vgl. @Woodruff2024[S. 2]), sind Wissensarbeitende von diesen Veränderungen unmittelbar betroffen. Darüber hinaus ermöglichen digitale Technologien einen erleichterten Zugang zu Informationen und unterstützen die Zusammenarbeit über räumliche Grenzen hinweg, beispielsweise durch digitale Kommunikations- und Kollaborationstechnologien (vgl. @Trenerry2021[S. 10]). Gleichzeitig verändern sich die Anforderungen an die Kompetenzen von Arbeitnehmenden, da digitale Fähigkeiten zunehmend notwendig werden, um Aufgaben in digitalen Arbeitsumgebungen ausführen zu können (vgl. @Trenerry2021[S. 7]). Dies betrifft insbesondere Wissensarbeitende, deren Tätigkeiten auf der Verarbeitung, Analyse und Nutzung von Informationen beruhen (vgl. @Woodruff2024[S. 2]).


*Merkmale der Wissensarbeit*

In der Literatur werden der Wissensarbeit häufig folgende Charakteristika zugeschrieben, die sie von manuellen oder rein administrativen Tätigkeiten abgrenzen:

- *Kognitive Intensität:* Wissensarbeit umfasst nicht-routinemäßige, kognitiv anspruchsvolle Aktivitäten, die auf der Erstellung, Anwendung oder Integration von spezialisierter intellektueller Expertise basieren (vgl. @DellAcqua2026[S. 4]).
- *Autonomie und Verantwortung:* Wissensarbeitende entscheiden innerhalb definierter Grenzen autonom über die Herangehensweise an eine Aufgabe und tragen die Verantwortung für die Produktivität ihrer Arbeit (vgl. @drucker1999knowledge[S. 87]).
- *Kontinuierliches Lernen:* Wissensarbeit erfordert die fortwährende Bereitschaft, bestehendes Wissen zu aktualisieren und neue Fähigkeiten zu erwerben, da sich die Anforderungen in digitalisierten Arbeitsumgebungen kontinuierlich verändern (vgl. @Drucker1994AgeOfSocialTransformation).

*Herausforderungen im digitalen Wandel*

Durch den Einzug von Large Language Models (LLMs) steht die Wissensarbeit vor einer tiefgreifenden Transformation, die neue *Herausforderungen* mit sich bringt.

+ *Die diskontinuierliche technologische Grenze (Jagged Frontier):* KI-Systeme zeigen in kognitiven Domänen eine ungleichmäßige Leistung. Während sie bei kreativen Aufgaben oft menschliche Experten übertreffen, können sie bei logisch ähnlich komplexen Aufgaben unvorhersehbar scheitern (vgl. @DellAcqua2026[S. 1]).
+ *Wandel zur Stewardship-Rolle:* Die Tätigkeit von Wissensarbeitenden verlagert sich von der Erstellung hin zur Überwachung und Integration von KI-Outputs, was eine erhöhte kritische Reflexionsfähigkeit erfordert (vgl. @Lee2025[S. 15]).
+ *Cognitive Offloading:* Die zunehmende Delegation kognitiver Aufgaben an KI-Systeme birgt die Gefahr einer Schwächung des kritischen Denkens sowie einer kognitiven Abhängigkeit (vgl. @Gerlich2025[S. 2]).
+ *Validierungsaufwand:* Da LLMs zu Halluzinationen und inhaltlich falschen, aber plausibel klingenden Ausgaben neigen, steigt der Aufwand für Verifizierungsprozesse (vgl. @Lee2025[S. 15]; @Brynjolfsson2025[S. 897]; @DellAcqua2026[S. 3]).

Um diese Herausforderungen einordnen zu können, bedarf es zunächst eines Überblicks über die technische Grundlage von LLMs sowie deren konkrete Einsatzmöglichkeiten in der Wissensarbeit.

== Textgenerierung mittels Künstlicher Intelligenz: Large Language Models und Einsatzmöglichkeiten

Large Language Models (LLMs) zählen zu den bedeutendsten Entwicklungen innerhalb der jüngeren KI-Forschung (vgl. @Bubeck2023SparksAGI[S. 4]). Es handelt sich dabei um neuronale Netzwerkmodelle, die anhand riesiger Mengen an Textdaten aus dem Internet trainiert werden. Das Modell lernt dabei, auf Basis eines gegebenen Kontextes die Wahrscheinlichkeit nachfolgender Tokens vorherzusagen (vgl. @Bubeck2023SparksAGI[S. 4]). Obwohl der Begriff menschliche Sprache impliziert, lassen sich diese Techniken auch auf andere Formen sequenzieller Daten anwenden, etwa Computercode, Proteinsequenzen oder Audiodaten (vgl. @Eloundou2023GPTsAreGPTs[S. 1]). Dabei bezeichnet der Begriff ein Modell, das auf extrem großen Datensätzen (oft im Tera- oder Petabyte-Bereich) trainiert wurde und über Milliarden von Parametern verfügt, um komplexe linguistische Strukturen abzubilden (vgl. @Woodruff2024[Fn. 1]; @bender2021stochastic[S. 610-623]).

*Technische Funktionsweise der Textgenerierung*

Der Kern der Textgenerierung basiert auf der *wahrscheinlichkeitsbasierten Vorhersage* des nächsten Wortes (bzw. Tokens) in einer Sequenz (vgl. @Brynjolfsson2025[S. 895]; @Chen2025[S. 14]). Der entscheidende Fortschritt gelang durch die Einführung von Transformer-Modellen, die einen sogenannten Attention-Mechanismus nutzen, der es dem System erlaubt, Wörtern innerhalb eines Textes unterschiedliche Relevanzgewichte zuzuweisen und so semantische Abhängigkeiten über weite Distanzen hinweg zu erfassen (vgl. @Chen2025[S. 14]; @Brynjolfsson2025[S. 896]). Anstatt expliziten linguistischen Regeln zu folgen, lernen diese Modelle durch statistische Korrelationen, welche Begriffe in einem bestimmten Kontext üblicherweise zusammen auftreten (vgl. @jiao2025generative[S. 1]; @Brynjolfsson2025[S. 896]).

*Einsatzmöglichkeiten in der Wissensarbeit*

Im Gegensatz zur diskriminativen KI, die primär Daten klassifiziert, erzeugt generative KI eigenständig neue Inhalte, die menschlichen Erzeugnissen in ihrer Qualität nahekommen (vgl. @Felten2023_Heterogeneity[S. 1]; @jiao2025generative[S. 2]). Aufgrund dieser Eigenschaften finden LLMs in der Wissensarbeit breite Anwendung, etwa bei der Texterstellung und Dokumentation, der Codegenerierung sowie der Zusammenfassung und Extraktion von Informationen aus umfangreichen Dokumenten (vgl. @Eloundou2023GPTsAreGPTs[S. 1 und 22]; @Noy2023ProductivityAI[S. 187-188]; @Chen2025[S. 14-15]).

Trotz dieser Potenziale bleibt die Herausforderung der *Halluzination* bestehen, da LLMs auf statistischen Wahrscheinlichkeiten für die Vorhersage des nächsten Tokens auf Basis des bisherigen Kontexts beruhen (vgl. @Brynjolfsson2025[S. 895]) und dadurch inhaltlich falsche Aussagen mit hoher sprachlicher Überzeugungskraft generieren können (vgl. @DellAcqua2026[S. 3]; @Woodruff2024[S. 7 und 23]). Eine kontinuierliche menschliche Validierung („Task Stewardship“) bleibt daher für die Qualitätssicherung in professionellen Kontexten unerlässlich (vgl. @Lee2025[S. 12–16]).
