= Einleitung

Generative Künstliche Intelligenz verbreitet sich zunehmend in der Arbeitswelt und verändert grundlegend, wie Wissensarbeit organisiert und ausgeführt wird (vgl. @Woodruff2024[S. 1-2]; @Trenerry2021[S. 1-2]). Insbesondere Large Language Models markieren dabei einen bedeutenden Entwicklungsschritt, da sie zunehmend Aufgabenbereiche erschließen, die bislang überwiegend menschlicher Expertise vorbehalten waren, wie etwa komplexes Sprachverständnis, kreative Textgenerierung und analytische Problemlösung (vgl. @DellAcqua2026[S. 1]; @Eloundou2023GPTsAreGPTs[S. 1-3]). Anders als frühere Automatisierungswellen, die vor allem manuelle und repetitive Tätigkeiten betrafen, richten sich diese Technologien unmittelbar an kognitive Kernaufgaben von Wissensarbeitenden. Erste empirische Studien belegen messbare Produktivitätssteigerungen beim Einsatz dieser Modelle, verweisen aber gleichzeitig auf Risiken durch fehlerhafte Ausgaben, Datenschutzbedenken und einen tiefgreifenden Wandel von Kompetenzanforderungen (vgl. @Noy2023ProductivityAI[S. 187-188]; @Lee2025[S. 15]; @Brynjolfsson2025[S. 897]).

== Problemstellung

Für Unternehmen wie SAP, die im Zentrum der digitalen Transformation von Geschäftsprozessen stehen und gleichzeitig eine wissensintensive Belegschaft beschäftigen, ist diese Entwicklung von unmittelbarer Relevanz. KI-Tools wie Large Language Models werden bei SAP bereits aktiv in Arbeitsprozessen eingesetzt, und der Einsatz wächst kontinuierlich. Dennoch fehlt bislang eine systematische Untersuchung, wie sich diese Nutzung konkret auf Arbeitsprozesse und Kompetenzprofile der Mitarbeitenden auswirkt und welche Chancen und Risiken sich daraus für die Organisation ergeben. Einerseits bergen Large Language Models erhebliche Potenziale zur Entlastung von Routinetätigkeiten und zur Aufwertung strategisch-inhaltlicher Arbeit. Andererseits arbeiten diese Systeme nicht deterministisch, neigen zu Halluzinationen und stellen neue Anforderungen an kritisches Denken, Datenschutzkompetenz und ethisches Urteilsvermögen, für die in vielen Unternehmen noch keine ausreichenden Strukturen bestehen. Daraus ergibt sich die zentrale Forschungsfrage dieser Arbeit, nämlich wie KI-Textgenerierung Arbeitsprozesse und Kompetenzprofile in der Wissensarbeit bei SAP verändert und welche Chancen und Risiken sich daraus ergeben.

== Zielsetzung und Aufbau der Arbeit

Die vorliegende Arbeit soll diese Frage beantworten, indem sie die Auswirkungen von KI-Textgenerierung auf die Wissensarbeit bei SAP systematisch analysiert und daraus konkrete Handlungsempfehlungen ableitet. Dazu folgt die Arbeit dem Einzelfallstudiendesign nach Yin und kombiniert zwei Erhebungsmethoden, nämlich eine systematische Literaturanalyse nach Snyder als sekundäre Evidenzbasis sowie leitfadengestützte Experteninterviews als primäre Erhebungsmethode.

Zu Beginn legte Kapitel 2 die theoretischen Grundlagen, indem es den Begriff der Wissensarbeit im digitalen Wandel definierte und Large Language Models in ihrer technischen Funktionsweise sowie ihren Einsatzmöglichkeiten einordnete. Das darauffolgende Kapitel 3 beschrieb das Forschungsdesign und erläuterte die methodische Vorgehensweise nach Yin. In der Prepare-Phase wurde dabei der Interviewleitfaden entwickelt und geeignete Interviewpartner wurden identifiziert. In der Collect-Phase wurden beide Methoden eingesetzt, wobei die systematische Literaturanalyse nach Snyder als sekundäre Evidenzbasis diente und die Experteninterviews als primäre Datenerhebung durchgeführt wurden. In der anschließenden Analyze-Phase wurden die Befunde beider Methoden mithilfe von Pattern Matching und Explanation Building zusammengeführt. Aufbauend darauf stellte Kapitel 4 die Ergebnisse der Literaturanalyse dar und beleuchtete Veränderungen in Arbeitsprozessen und Kompetenzprofilen sowie die damit verbundenen Chancen und Risiken. Im anschließenden Kapitel 5 wurden die Ergebnisse der Experteninterviews mit vier Wissensarbeitenden bei SAP präsentiert, mit der Literatur abgeglichen und in Handlungsempfehlungen für die Organisation überführt. Abgeschlossen wird die Arbeit durch Kapitel 6 mit einer Zusammenfassung der zentralen Erkenntnisse und einem Ausblick auf weiterführende Forschungsfragen.

Die Arbeit unterliegt dabei einigen methodischen Einschränkungen. Als Einzelfallstudie mit vier Interviewpartnerinnen und Interviewpartnern, von denen drei aus derselben Organisationseinheit stammen, sind die Ergebnisse nicht ohne Weiteres auf andere Unternehmen übertragbar. Darüber hinaus entwickelt sich das Forschungsfeld der generativen KI außergewöhnlich schnell, sodass die Befunde als Momentaufnahme zu verstehen sind und keinen Anspruch auf abschließende Gültigkeit erheben können.
