= Einleitung

Die fortschreitende Digitalisierung der Arbeitswelt führt zu grundlegenden Veränderungen von Arbeitstätigkeiten und -abläufen und schafft damit neue Rahmenbedingungen für die Wissensarbeit (vgl. @Arlinghaus2017[S.2]). Anders als frühere Digitalisierungsschritte, die vor allem repetitive Tätigkeiten betrafen, zielt mit generativer KI die Veränderung erstmals unmittelbar auf kognitive Kernaufgaben von Wissensarbeitenden ab (vgl. @DellAcqua2026[S. 1]; @Eloundou2023GPTsAreGPTs[S. 1-3]). Für Unternehmen wie SAP, deren Wertschöpfung wesentlich auf wissensintensiver Arbeit beruht, ergibt sich daraus eine unmittelbare strategische Relevanz. Wie diese Werkzeuge Arbeitsprozesse und Kompetenzprofile verändern und welche Chancen sowie Risiken damit verbunden sind, ist für die Gestaltung zukunftsfähiger Arbeitsumgebungen von zentraler Bedeutung.

== Problemstellung

Für Unternehmen wie SAP, die im Zentrum der digitalen Transformation von Geschäftsprozessen stehen und gleichzeitig eine wissensintensive Belegschaft beschäftigen, ist diese Entwicklung von besonderer Tragweite. KI-Tools wie Large Language Models werden bei SAP bereits aktiv in Arbeitsprozessen eingesetzt, und der Einsatz wächst kontinuierlich. Dennoch fehlt bislang eine systematische Untersuchung, wie sich diese Nutzung konkret auf Arbeitsprozesse und Kompetenzprofile der Mitarbeitenden auswirkt und welche Chancen und Risiken sich daraus für die Organisation ergeben. In der Praxis zeigt sich, dass diese Werkzeuge einerseits als Entlastung bei Routinetätigkeiten wahrgenommen werden und Potenziale für eine Aufwertung strategisch-inhaltlicher Arbeit vermuten lassen. Andererseits treten in der alltäglichen Nutzung Unsicherheiten zutage, da die Ausgaben dieser Systeme sich als nicht immer verlässlich erweisen und der sachgerechte Umgang Mitarbeitende vor neue Anforderungen an kritisches Denken, Datenschutzkompetenz und ethisches Urteilsvermögen stellt, für die bei SAP bislang keine ausreichenden Strukturen erkennbar sind. Daraus ergibt sich die zentrale Forschungsfrage dieser Arbeit: _„Wie verändert KI-Textgenerierung Arbeitsprozesse und Kompetenzprofile in der Wissensarbeit bei SAP, und welche Chancen und Risiken ergeben sich daraus für die Organisation?“_

== Zielsetzung und Aufbau der Arbeit

Die vorliegende Arbeit soll diese Frage beantworten, indem sie die Auswirkungen von KI-Textgenerierung auf die Wissensarbeit bei SAP systematisch analysiert und daraus konkrete Handlungsempfehlungen ableitet. Dazu folgt die Arbeit dem Einzelfallstudiendesign nach Yin und kombiniert zwei Erhebungsmethoden, nämlich eine systematische Literaturanalyse nach Snyder als sekundäre Evidenzbasis sowie leitfadengestützte Experteninterviews als primäre Erhebungsmethode.

Kapitel 2 legt die theoretischen Grundlagen, indem es den Begriff der Wissensarbeit im digitalen Wandel definiert und Large Language Models in ihrer technischen Funktionsweise sowie ihren Einsatzmöglichkeiten einordnet. Das darauffolgende Kapitel 3 beschreibt das Forschungsdesign und erläutert die methodische Vorgehensweise nach Yin. Es begründet zunächst die Wahl der Einzelfallstudie als Forschungsdesign und beschreibt den sechsphasigen Prozess nach Yin. In der Prepare-Phase wird der Interviewleitfaden entwickelt und geeignete Interviewpartner werden identifiziert. In der Collect-Phase kommen beide Methoden zum Einsatz, wobei die systematische Literaturanalyse nach Snyder als sekundäre Evidenzbasis dient und die Experteninterviews als primäre Datenerhebung durchgeführt werden. In der anschließenden Analyze-Phase werden die Befunde beider Methoden mithilfe von Pattern Matching und Explanation Building zusammengeführt. Die Share-Phase umfasst schließlich die Aufbereitung und Kommunikation der Ergebnisse in der vorliegenden Arbeit. Aufbauend darauf stellt Kapitel 4 die Ergebnisse der Literaturanalyse dar und beleuchtet Veränderungen in Arbeitsprozessen und Kompetenzprofilen sowie die damit verbundenen Chancen und Risiken. Im anschließenden Kapitel 5 werden die Ergebnisse der Experteninterviews mit vier Wissensarbeitenden bei SAP präsentiert, mit der Literatur abgeglichen und in Handlungsempfehlungen für die Organisation überführt. Abgeschlossen wird die Arbeit durch Kapitel 6 mit einer Zusammenfassung der zentralen Erkenntnisse und einem Ausblick auf weiterführende Forschungsfragen.

Die Arbeit unterliegt dabei einigen methodischen Einschränkungen. Als Einzelfallstudie mit vier Interviewpartnerinnen und Interviewpartnern, von denen drei aus derselben Organisationseinheit stammen, sind die Ergebnisse nicht ohne Weiteres auf andere Unternehmen übertragbar. Darüber hinaus entwickelt sich das Forschungsfeld der generativen KI außergewöhnlich schnell, sodass die Befunde als Momentaufnahme zu verstehen sind und keinen Anspruch auf abschließende Gültigkeit erheben können.
