= Einleitung

Die moderne Arbeitswelt steht am Beginn einer neuen technologischen Ära, die oft als fünfte industrielle Revolution begriffen wird und durch eine verstärkte Synergie zwischen menschlicher Kreativität und Künstlicher Intelligenz (KI) geprägt ist (vgl. McKinsey2026[S. 3]). Während vorangegangene Automatisierungswellen primär manuelle und routinemäßige Tätigkeiten betrafen, zielt Generative KI (GenAI) nun direkt auf die Domäne der Wissensarbeit ab (vgl. @DellAcqua2026[S. 3]; @Eloundou2023GPTsAreGPTs[S. 1]).

Das enorme Aufsehen um Large Language Models (LLMs) wie ChatGPT begründet sich in der Fähigkeit dieser Systeme, komplexe Aufgaben zu übernehmen, die bisher menschliche Diskretion, tiefes Sprachverständnis und die Anwendung von implizitem Wissen erforderten (vgl. @Brynjolfsson2025[S. 890]; @Woodruff2024[S. 1]). Aktuelle Analysen deuten darauf hin, dass GenAI in bestimmten Funktionsbereichen das Potenzial hat, in frühen Szenarien bis zu 70~% der heutigen Arbeitszeit technisch zu automatisieren (vgl. McKinsey2026[S. 5]; @Eloundou2023GPTsAreGPTs[S. 1]). Für Unternehmen ergibt sich daraus die dringliche Notwendigkeit, sowohl allgemeine Sprachmodelle als auch spezialisierte relationale Modelle zur Analyse strukturierter Geschäftsdaten zu evaluieren und in bestehende Arbeitsprozesse zu integrieren (vgl. McKinsey2026[S. 20]; @Agrawal2024[S. 327]).

== Problemstellung und Relevanz

In der heutigen globalisierten Wirtschaft gilt Wissen als die *zentrale Ressource* und als der entscheidende Faktor für langfristige Wettbewerbsvorteile von Unternehmen (vgl. @Kusterer2008[S. 1]). Während die Informationstechnologie die Wissensarbeit seit Jahrzehnten unterstützt, markiert der Durchbruch generativer Künstlicher Intelligenz, insbesondere durch Large Language Models (LLMs), einen fundamentalen Wendepunkt (vgl. @Woodruff2024[S. 2]). Diese Technologien dringen zunehmend in Domänen vor, die bisher als *ausschließlich menschliches Terrain* galten, wie etwa komplexes Sprachverständnis, kreative Textgenerierung und analytische Problemlösung (vgl. @DellAcqua2026[S. 1]; @Eloundou2023GPTsAreGPTs[S. 1]).

Für ein Softwareunternehmen wie *SAP*, das im Zentrum der digitalen Transformation von Geschäftsprozessen steht, ist diese Entwicklung von doppelter Relevanz: Einerseits versprechen LLMs massive *Produktivitätspotenziale*. Studien belegen, dass der Einsatz von KI-Assistenten die Produktivität bei komplexen Schreib- und Programmieraufgaben signifikant steigern kann, wobei Zeiteinsparungen von etwa 0,75 Standardabweichungen beobachtet wurden (vgl. @Noy2023ProductivityAI[S. 187]; @Brynjolfsson2025[S. 890]). Besonders bemerkenswert ist dabei die Fähigkeit der KI, als *„Equalizer"* zu fungieren, indem sie insbesondere weniger erfahrenen Mitarbeitern hilft, die Lernkurve schneller zu durchlaufen und Best-Practice-Muster erfolgreicher Experten zu adaptieren (vgl. @Brynjolfsson2025[S. 917]; @DellAcqua2026[S. 8]).

Demgegenüber steht die Herausforderung einer *„gezackten technologischen Grenze"* (Jagged Technological Frontier): LLMs zeigen eine beeindruckende Leistung bei bestimmten kreativen Aufgaben, scheitern jedoch unvorhersehbar an scheinbar einfachen logischen oder kontextspezifischen Problemen (vgl. @DellAcqua2026[S. 1]). Die daraus resultierenden *Halluzinationen* — fachlich korrekt klingende, aber inhaltlich falsche Ausgaben — stellen in einem hochsensiblen Geschäftsumfeld ein erhebliches Risiko dar (vgl. @Woodruff2024[S. 2]; @Lee2025[S. 2]). Hinzu kommen kritische Fragen der *Datensicherheit* und des Schutzes von geistigem Eigentum, da LLMs oft auf Basis sensibler Unternehmensdaten agieren (vgl. McKinsey2026[S. 20]).

Zudem löst der Einsatz von KI einen tiefgreifenden *Kompetenzwandel* aus. Wissensarbeitende verlagern ihre Tätigkeit zunehmend von der Erstellung von Inhalten hin zu deren *Überwachung und Integration* („Task Stewardship"), was eine verstärkte kognitive Anstrengung bei der Verifizierung von KI-Outputs erfordert (vgl. @Lee2025[S. 2]). In Anbetracht dieser Spannungsfelder zwischen technologischem Fortschritt und operationalen Risiken widmet sich die vorliegende Arbeit der zentralen Fragestellung:

*Wie verändern Large Language Models die Wissensarbeit bei SAP, und welche konkreten Handlungsempfehlungen lassen sich für Unternehmen und Mitarbeiter ableiten — angesichts erheblicher Produktivitätspotenziale, aber gleichzeitiger Risiken durch Halluzinationen, Datenschutz und Kompetenzwandel?*

== Zielsetzung und Aufbau der Arbeit

Das zentrale Ziel dieser Arbeit ist es, die Auswirkungen von Large Language Models auf die Wissensarbeit bei SAP systematisch zu analysieren und daraus konkrete Handlungsempfehlungen für Arbeitsprozesse, Kompetenzprofile und den zukünftigen KI-Einsatz abzuleiten. Um dieses Ziel zu erreichen, werden drei Erkenntnisdimensionen verfolgt. Zunächst soll der aktuelle Stand der Forschung zur Transformation der Wissensarbeit durch generative KI aufgearbeitet werden. Darauf aufbauend sollen die durch LLMs ausgelösten Veränderungen in Arbeitsabläufen und Kompetenzanforderungen bei SAP identifiziert werden. Schließlich sollen fundierte Handlungsempfehlungen entwickelt werden, die als Leitfaden für eine nachhaltige Integration von LLMs in den Arbeitsalltag dienen.

Entsprechend dieser Zielsetzung gliedert sich die Arbeit in sechs Kapitel. Zunächst legt Kapitel 2 die theoretischen Grundlagen, indem es den Begriff der Wissensarbeit im digitalen Wandel definiert und Large Language Models technisch einordnet. Anschließend beschreibt Kapitel 3 das Forschungsdesign und erläutert die methodische Vorgehensweise, die auf einer Fallstudienanalyse nach Yin basiert und eine systematische Literaturanalyse mit qualitativen Experteninterviews verbindet. Darauf aufbauend stellt Kapitel 4 die Ergebnisse der Literaturanalyse dar, mit Fokus auf Veränderungen von Arbeitsprozessen und Kompetenzprofilen sowie den damit verbundenen Chancen und Risiken. Ergänzend dazu präsentiert Kapitel 5 die empirischen Ergebnisse der Experteninterviews und gleicht diese mit der Literatur ab, um spezifische Handlungsempfehlungen für SAP abzuleiten. Kapitel 6 schließt die Arbeit schließlich mit einer Zusammenfassung der zentralen Erkenntnisse und einem Ausblick auf die zukünftige Entwicklung der KI-gestützten Wissensarbeit ab.
