= Forschungsdesign und Vorgehensweise

Das folgende Kapitel legt das Forschungsdesign der vorliegenden Arbeit dar und erläutert die gewählten methodischen Vorgehensweisen. Dabei wird zunächst die Fallstudienanalyse nach Yin als übergeordnetes Forschungsdesign beschrieben, bevor das Vorgehen der systematischen Literaturanalyse nach Snyder sowie die Durchführung der leitfadengestützten Experteninterviews erläutert werden.

== Fallstudienanalyse nach Yin

Yin definiert die Fallstudie entlang zweier zentraler Dimensionen, nämlich dem Untersuchungsgegenstand einerseits und den methodischen Merkmalen andererseits. Hinsichtlich des Untersuchungsgegenstands handelt es sich bei einer Fallstudie um eine empirische Untersuchung, die ein Phänomen oder einen Fall eingehend und in seinem realen Kontext analysiert. In methodischer Hinsicht zeichnet sich die Fallstudie dadurch aus, dass sie die technisch besondere Situation berücksichtigt, in der mehr relevante Variablen als verfügbare Datenpunkte vorliegen. Um dieser Komplexität gerecht zu werden, stützt sie sich auf mehrere Evidenzquellen, deren Daten durch Triangulation zusammengeführt werden. Insgesamt erweist sich die Fallstudie damit als eine ganzheitliche Forschungsmethode, die Designlogik, Datenerhebung und Datenanalyse gleichermaßen umfasst und folglich nicht auf ein bloßes Erhebungsinstrument reduziert werden kann (vgl. @Yin2014[S. 33]).

*Arten von Fallstudien*

Fallstudien können drei verschiedenen Forschungszwecken dienen. Explorative Fallstudien zielen darauf ab, erste Hypothesen für eine weiterführende Untersuchung zu entwickeln. Deskriptive Fallstudien beschreiben ein Phänomen innerhalb seines Kontextes vollständig. Explanatorische Fallstudien hingegen erklären kausale Zusammenhänge (vgl. @Yin2014[S. 23]). Die vorliegende Arbeit folgt einem deskriptiven Ansatz, da sie das noch kaum empirisch dokumentierte Phänomen des LLM-Einsatzes in der Wissensarbeit innerhalb des organisationalen Kontexts von SAP erstmals systematisch beschreibt.

Ein weiteres Unterscheidungsmerkmal betrifft die Anzahl der untersuchten Fälle. Bei der Einzelfallstudie konzentriert sich die Analyse auf einen einzigen Fall, was sich dann anbietet, wenn dieser besonders erkenntnisreich ist, einen Extremfall darstellt oder einen seltenen Zugang zum Untersuchungsgegenstand ermöglicht (vgl. @EisenhardtGraebner2007[S. 25-27]). Die Mehrfachfallstudie erweitert diesen Ansatz um mehrere Fälle und ermöglicht so fallübergreifende Aussagen (vgl. @Yin2014[S. 45]).

Der Forschungsprozess nach Yin gliedert sich in sechs aufeinander aufbauende Phasen, nämlich Plan, Design, Prepare, Collect, Analyze und Share, die den gesamten Ablauf von der ersten Konzeption bis zur abschließenden Kommunikation der Ergebnisse strukturieren.

*Plan*

In der Plan-Phase wird grundlegend geklärt, ob die Fallstudie als Forschungsmethode für das jeweilige Erkenntnisinteresse geeignet ist. Nach Yin spricht für ihren Einsatz, wenn die Forschungsfragen auf ein Wie oder Warum abzielen, der Forscher keinen Einfluss auf das untersuchte Geschehen nehmen kann und ein gegenwärtiges Phänomen im Mittelpunkt steht (vgl. @Yin2014[S. 3]).

*Design*

Die Designphase verfolgt das Ziel, logische Inkonsistenzen im Forschungsaufbau zu vermeiden und sicherzustellen, dass die erhobenen Daten tatsächlich zur Beantwortung der Forschungsfrage beitragen (vgl. @Yin2014[S. 61]). In der vorliegenden Arbeit wurde das Design auf Basis der Forschungsfrage und der gewählten Einzelfallstudie mit Wissensarbeitenden bei SAP als Untersuchungseinheit festgelegt.

*Prepare*

Die Prepare-Phase dient der Vorbereitung der Datenerhebung, einschließlich der Erstellung eines Fallstudienprotokolls zur Sicherung der Reliabilität (vgl. @Yin2014[S. 84f]). Da die Untersuchungseinheit von Beginn an feststand, war ein aufwändiges Screening nicht erforderlich. Auf eine Pilotstudie wurde verzichtet, da der Forscher als internes Mitglied der SAP-Organisation über einen Feldzugang verfügte, der diese konzeptionelle Funktion bereits erfüllte (vgl. @Yin2014[S. 96]).

*Collect*

In der Collect-Phase erfolgt die eigentliche Datenerhebung. Yin empfiehlt dabei die Kombination möglichst vieler Datenquellen für eine belastbarere Evidenzbasis (vgl. @Yin2014[S. 106f]). In der vorliegenden Arbeit werden Experteninterviews als primäre Erhebungsmethode sowie wissenschaftliche und praxisorientierte Literatur als sekundäre Evidenzbasis kombiniert. Weitere Quellen wie direkte Beobachtung oder Archivdaten konnten aufgrund des auf Interviews begrenzten Feldzugangs nicht einbezogen werden.

*Analyze*

In der Analyzephase werden die erhobenen Belege systematisch ausgewertet, um fundierte Erkenntnisse abzuleiten (vgl. @Yin2014[S. 133]). In der vorliegenden Arbeit kommen zwei von Yins fünf Analysetechniken zum Einsatz. Pattern Matching dient als primäre Technik, bei der die theoretischen Muster aus der Literaturanalyse mit den empirischen Interviewbefunden abgeglichen werden. Eine Übereinstimmung stärkt dabei die interne Validität der Ergebnisse (vgl. @Yin2014[S. 143]). Diesem Abgleich liegt das wissenschaftstheoretische Prinzip der Falsifikation nach Karl Popper zugrunde, wonach eine empirische Aussage dann als prüfbar gilt, wenn sie durch Beobachtungen grundsätzlich widerlegbar ist (vgl. @popper2005lesebuch). Die aus der Literaturanalyse abgeleiteten Muster werden in Kapitel 5 als falsifizierbare Aussagen behandelt und daraufhin geprüft, ob die Interviewbefunde ihnen widersprechen. Aussagen, die sich durch die Praxisperspektiven nicht falsifizieren lassen, gelten dabei als empirisch gestützt, ohne jedoch den Anspruch auf abschließende Bestätigung zu erheben. Ergänzend wird Explanation Building eingesetzt, um iterativ eine konsistente Erklärung dafür zu entwickeln, wie LLMs die Wissensarbeit bei SAP verändern (vgl. @Yin2014[S. 147f]).

*Share*

Als abschließender Schritt umfasst die Share-Phase die Aufbereitung und Kommunikation der Erkenntnisse in einer linear-analytischen Struktur, die von der Forschungsfrage über Methodik und Daten bis zu Befunden und Schlussfolgerungen logisch aufgebaut ist (vgl. @Yin2014[S. 188, 205]).

Grundsätzlich waren für diese Arbeit auch alternative Forschungsdesigns denkbar, etwa eine Mehrfachfallstudie oder ein quantitatives Umfragedesign. Dennoch erweist sich die Einzelfallstudie nach Yin als am besten geeignet, weil die Rollentransformation ein zeitgenössisches Phänomen darstellt, das nicht losgelöst von seinem organisationalen Kontext betrachtet werden kann, und weil eine quantitative Erhebung voraussetzen würde, dass die relevanten Variablen bereits bekannt sind. SAP erfüllt dabei Yins Kriterium eines Revelatory Case, da der Forscher als internes Mitglied der SAP-Organisation einen Feldzugang zu einem Phänomen besitzt, das externen Forschern bislang weitgehend verschlossen ist. Der reale Einsatz von Large Language Models in der Wissensarbeit eines Großunternehmens ist empirisch kaum dokumentiert, sodass bereits die deskriptiven Befunde einen eigenständigen Erkenntniswert besitzen (vgl. @Yin2014[S. 52]). Als Analyseeinheit werden dabei Wissensarbeitende bei SAP definiert, die im Rahmen ihrer beruflichen Tätigkeit aktiv Large Language Models einsetzen.

Die Kombination aus systematischer Literaturanalyse und Experteninterviews wurde dabei bewusst gewählt, weil weder eine reine Literaturanalyse noch ein alleiniges Interviewdesign das Erkenntnisinteresse dieser Arbeit vollständig erfüllen kann. Eine reine Literaturanalyse ermöglicht zwar einen fundierten theoretischen Überblick, trifft aber keine Aussage darüber, ob die beschriebenen Veränderungen im konkreten Unternehmenskontext von SAP tatsächlich eintreten. Umgekehrt erlauben Interviews ohne theoretische Fundierung keine Einordnung der Praxiserfahrungen in einen übergeordneten Forschungsstand. Erst die Kombination beider Methoden ermöglicht es, theoretische Muster aus der Literatur zu identifizieren und ihre Gültigkeit im spezifischen Unternehmenskontext empirisch zu prüfen.

== Systematische Literaturanalyse

*Methodisches Vorgehen der Literaturanalyse nach Snyder*

Um für die Untersuchung der Wissensarbeit bei SAP eine valide und reproduzierbare Grundlage zu schaffen, folgt diese Arbeit dem methodischen Rahmen von @Snyder2019. Da im Rahmen dieser Arbeit festgestellt wurde, dass das Forschungsfeld der generativen Künstlichen Intelligenz durch eine hohe Entwicklungsgeschwindigkeit und ein breites fachübergreifendes Spektrum geprägt ist, eignet sich dieser Ansatz besonders, da er nicht auf rein quantitative Methoden beschränkt ist, sondern auch die gemeinsame Auswertung von Quellen aus unterschiedlichen Forschungsrichtungen ermöglicht (vgl. @Snyder2019[S. 334]). Das Vorgehen gliedert sich dabei in den vierphasigen Prozess aus Design, Durchführung, Analyse und Verschriftlichung (vgl. @Snyder2019[S. 336-337]).

In der ersten Phase, dem Review-Design, wird ein integrativer Ansatz gewählt, der sich nach Snyder besonders für neue Themenbereiche eignet, in denen noch kein etabliertes theoretisches Modell existiert (vgl. @Snyder2019[S. 336]). Die wissenschaftliche Suche erfolgte in den Datenbanken Google Scholar, arXiv, ResearchGate sowie dem Bibliothekskatalog der DHBW Ravensburg. Praxisorientierte Quellen wurden über gezielte Recherche identifiziert und auf Basis festgelegter Ein- und Ausschlusskriterien bewertet (vgl. @Snyder2019[S. 337]).

In der zweiten Phase der Durchführung wurde die Literatursuche anhand der festgelegten Strategie umgesetzt. Die Quellenauswahl erfolgte in zwei Stufen, bei denen zunächst Titel und Abstract und anschließend der Volltext auf Relevanz geprüft wurden. Da der von Snyder empfohlene Einsatz von zwei Reviewern im Rahmen einer Einzelarbeit nicht realisierbar war, wird diesem Umstand durch die explizite Dokumentation der Auswahlkriterien begegnet (vgl. @Snyder2019[S. 337]).

In der dritten Phase, der Analyse, wurden die Quellen konzeptzentriert ausgewertet, sodass Themen wie Veränderung von Arbeitsprozessen, Kompetenzwandel und Chancen und Risiken über verschiedene Quellenkategorien hinweg extrahiert und miteinander verglichen werden konnten (vgl. @Snyder2019[S. 337]).

In der abschließenden Phase der Verschriftlichung werden Motivation, Vorgehen und Erkenntnisse des Reviews so dokumentiert, dass der Leser die Qualität und Verlässlichkeit der Ergebnisse nachvollziehen kann (vgl. @Snyder2019[S. 337]). Der Beitrag dieser Arbeit besteht darin, einen strukturierten Überblick über den aktuellen Wissensstand zur Veränderung der Wissensarbeit durch KI-Textgenerierung zu schaffen.

*Zielsetzung und Vorgehen*

Die vorliegende Arbeit untersucht die in Abschnitt 1.1 formulierte Forschungsfrage, wie KI-Textgenerierung mittels Large Language Models Arbeitsprozesse und Kompetenzprofile in der Wissensarbeit bei SAP verändert sowie welche Chancen und Risiken sich daraus ergeben. Die Literaturanalyse kombiniert dazu drei Quellenkategorien, die zwei unterschiedliche Funktionen erfüllen, nämlich die theoretisch-methodische Fundierung durch wissenschaftliche Studien einerseits sowie die Abbildung empirischer Aktualität und Praxisrelevanz durch Berater- und Fachpressequellen andererseits.

Die einbezogene Literatur lässt sich dabei in drei Kategorien unterteilen. Wissenschaftliche Literatur in Form von peer-reviewten Studien und Working Papern bildet die theoretische Basis der Arbeit und liefert methodisch abgesicherte Erkenntnisse zu Automatisierungspotenzialen und Produktivitätseffekten. Beratungsstudien (graue Literatur) großer Institute liefern ergänzend aktuelle, breit angelegte empirische Daten zu Skill-Wandel oder Adoptionsraten, die wissenschaftlich oft noch nicht verfügbar sind. Fachpresse und Praxisbeiträge runden das Bild punktuell ab, indem sie die praktische Rezeption der Entwicklungen in Unternehmen abbilden. Da geeignete Fachpressebeiträge im Zuge der Recherche nur vereinzelt identifiziert werden konnten, stützt sich die Analyse in diesem Bereich überwiegend auf Beratungsstudien.

Zur Sicherung der Quellenqualität werden spezifische Auswahlkriterien angelegt. Neben einer strikten Aktualität (Fokus auf 2023–2026, mit Ausnahme definitorischer Grundlagen) wird bei Beratungsstudien die Transparenz der Methodik (Stichprobengröße, Erhebungszeitraum) geprüft. Um eine einseitige Darstellung zu vermeiden, wird auf Ausgewogenheit geachtet, indem auch kritische Gegenpositionen zum KI-Einsatz in Unternehmen einbezogen werden. Reine Meinungsbeiträge ohne empirische Grundlage werden ausgeschlossen.

Diese einbezogenen Beratungsquellen stellen keine peer-reviewte Literatur im engeren Sinne dar und sind entsprechend kritisch zu würdigen. Insbesondere bei Studien von Unternehmensberatungen ist ein potenzieller Interessenkonflikt zu berücksichtigen, da diese Institute selbst kommerzielle KI-Transformationsleistungen anbieten. Dieser methodischen Einschränkung wird dadurch begegnet, dass Beratungsquellen stets in Verbindung mit wissenschaftlichen Quellen herangezogen werden und ihre empirischen Befunde nur dort als eigenständige Belege gelten, wo vergleichbare wissenschaftliche Daten aufgrund der Aktualität des Forschungsfelds noch nicht verfügbar sind.

== Experteninterviews

Als eine der zentralen Methoden qualitativer Forschung findet das Experteninterview in unterschiedlichen Forschungsfeldern Anwendung und kann dabei sowohl als eigenständiges Instrument als auch in Kombination mit weiteren Forschungsmethoden eingesetzt werden (vgl. @Burger2011[S. 127]). Im Mittelpunkt steht die gezielte Erschließung des Fachwissens ausgewählter Experten, um auf dieser Basis wissenschaftlich fundierte Erkenntnisse zu gewinnen (vgl. @Bogner2014[S. 17]).

Leitfadengestützte Experteninterviews zählen zu den qualitativen Methoden der Datenerhebung und fokussieren auf das Fachwissen und die Praxiserfahrung der befragten Personen, um zielgerichtete und komplexe Fragestellungen zu erschließen, die für Außenstehende nur schwer zugänglich sind (vgl. @BaurBlasius2022[S. 888–889]). Die gewählte halbstrukturierte Form orientiert sich an einem Leitfaden, lässt jedoch gleichzeitig Raum für ergänzende Fragen und verbindet so die Vorteile standardisierter und offener Befragungen (vgl. @RennerJacob2020[S. 13–17]).

Der Leitfaden strukturiert den Ablauf aller Gespräche und ermöglicht so eine einheitliche Gesprächsführung. Er kann Erzählaufforderungen, vorformulierte Fragen sowie Stichpunkte enthalten und bei Bedarf auch Stimuli wie Bilder oder Geschichten einbeziehen. Dabei wird stets eine Balance zwischen Offenheit und Struktur angestrebt. Bei der Erstellung empfiehlt sich ein dreistufiges Vorgehen, bei dem zunächst möglichst offene Fragen gestellt werden, die dem Befragten freie Antworten ermöglichen und so alle relevanten Informationen erschließen. Anschließend können gezielte Nachfragen zu Themen gestellt werden, die bisher unbeantwortet oder unzureichend behandelt wurden. Abschließend werden vorformulierte Fragen in einer logischen Reihenfolge an den Interviewten gerichtet (vgl. @BaurBlasius2022[S. 881–883]).

Als Experten können Personen herangezogen werden, die über ein überdurchschnittliches, umfangreiches Wissen oder eine besondere fachliche Tiefe in einem bestimmten Bereich verfügen. Dies umfasst sowohl Insiderwissen, das für Außenstehende nur schwer zugänglich ist, als auch einen allgemein vertieften Wissensstand im jeweiligen Fachgebiet. Expertenwissen beschränkt sich dabei nicht auf die Berufswelt, sodass auch Personen, die sich ein spezifisches Thema eigenständig erschlossen oder darin besondere Fähigkeiten entwickelt haben, in diesen Bereichen als Experten gelten können. Im Mittelpunkt der Interviews steht die fachliche Expertise der Befragten und nicht ihre persönliche Lebenssituation. Den Interviewpartnern wird dabei verdeutlicht, welche bedeutsame Rolle ihr Wissen für die Beantwortung der Forschungsfrage einnimmt (vgl. @BaurBlasius2022[S. 887–888]).

Die Auswertung der Experteninterviews erfolgt nach dem Verfahren der strukturierenden Inhaltsanalyse nach Mayring. Dabei wird ein Kategoriensystem deduktiv aus den Befunden der Literaturanalyse abgeleitet, sodass die drei übergeordneten Themenbereiche Veränderungen von Arbeitsprozessen, Kompetenzprofile sowie Chancen und Risiken als Hauptkategorien dienen. Auf dieser Grundlage werden die relevanten Aussagen aus den Interviewtranskripten den jeweiligen Kategorien zugeordnet und thematisch ausgewertet (vgl. @Mayring2014[S. 95f]).

In der vorliegenden Arbeit wurden vier Wissensarbeitende bei SAP als Experten befragt, die Large Language Models aktiv und regelmäßig in ihren beruflichen Alltag integriert haben. Drei der Befragten sind in einer internen Beratungseinheit von SAP tätig und decken beratungs- sowie projektnahe Tätigkeitsfelder ab, während die vierte Person als Senior Developer im Bereich S/4HANA Cloud eine technische Entwicklungsperspektive einbringt. Ihre Expertise ergibt sich damit nicht aus einer formalen Zertifizierung, sondern aus dem praktisch aufgebauten Erfahrungswissen im konkreten Einsatz von KI-Tools im Unternehmenskontext. Die Durchführung und Auswertung der Interviews werden in Kapitel 5 dargestellt.

