= Forschungsdesign und Vorgehensweise

Eine Methode beschreibt eine systematische Vorgehensweise, mit der innerhalb eines festgelegten Ziels Erkenntnisse gewonnen werden können. Dabei zeichnen sich Methoden durch verschiedene charakteristische Merkmale aus. Zunächst ist entscheidend, dass eine Methode auch für Personen nachvollziehbar ist, die bisher keine Kenntnisse über deren Anwendung besitzen. Darüber hinaus sollte die Durchführung unabhängig von der jeweiligen Person immer zu vergleichbaren Ergebnissen führen.

Des Weiteren basieren Methoden auf einem klar strukturierten und durchdachten Prinzip, wodurch eine objektive Vorgehensweise ermöglicht wird. Folglich werden persönliche Annahmen oder subjektive Einschätzungen, die bereits im Vorfeld entstanden sind, nicht in die Bewertung einbezogen. Abschließend ist es wichtig, dass Methoden nach einheitlichen Grundsätzen aufgebaut sind, sodass sie vermittelbar, erlernbar und wiederholbar bleiben (vgl. @balzert2009lehrbuch[S. 53]).

== Fallstudienanalyse nach Yin

Yin definiert die Fallstudie entlang zweier zentraler Dimensionen, nämlich dem Untersuchungsgegenstand einerseits und den methodischen Merkmalen andererseits. Hinsichtlich des Untersuchungsgegenstands handelt es sich bei einer Fallstudie um eine empirische Untersuchung, die ein Phänomen oder einen Fall eingehend und in seinem realen Kontext analysiert. In methodischer Hinsicht zeichnet sich die Fallstudie dadurch aus, dass sie die technisch besondere Situation berücksichtigt, in der mehr relevante Variablen als verfügbare Datenpunkte vorliegen. Um dieser Komplexität gerecht zu werden, stützt sie sich auf mehrere Evidenzquellen, deren Daten durch Triangulation zusammengeführt werden. Insgesamt erweist sich die Fallstudie damit als eine ganzheitliche Forschungsmethode, die Designlogik, Datenerhebung und Datenanalyse gleichermaßen umfasst und folglich nicht auf ein bloßes Erhebungsinstrument reduziert werden kann (vgl. @Yin2014[S. 33]).

*Arten von Fallstudien*

Fallstudien können drei verschiedenen Forschungszwecken dienen. Explorative Fallstudien zielen darauf ab, erste Hypothesen für eine weiterführende Untersuchung zu entwickeln. Deskriptive Fallstudien beschreiben ein Phänomen innerhalb seines Kontextes vollständig. Explanatorische Fallstudien hingegen erklären kausale Zusammenhänge (vgl. @Yin2014[S. 23]).

Ein weiteres Unterscheidungsmerkmal betrifft die Anzahl der untersuchten Fälle. Bei der Einzelfallstudie konzentriert sich die Analyse auf einen einzigen Fall, was sich dann anbietet, wenn dieser besonders erkenntnisreich ist, einen Extremfall darstellt oder einen seltenen Zugang zum Untersuchungsgegenstand ermöglicht. Auf diese Weise lässt sich die Existenz eines Phänomens unter außergewöhnlichen Bedingungen gezielt und tiefgehend untersuchen (vgl. @EisenhardtGraebner2007[S. 25-27]). Die Mehrfachfallstudie erweitert diesen Ansatz, indem sie mehrere Fälle einbezieht und auf dieser Grundlage fallübergreifende Aussagen ableitet (vgl. @Yin2014[S. 45]). Der Vergleich verschiedener Fälle erlaubt es zu beurteilen, ob ein Ergebnis fallspezifisch ist oder sich auf andere Kontexte übertragen lässt. Die Fallauswahl erfolgt dabei bewusst, um theoretische Annahmen zu stützen, weiterzuentwickeln, zu kontrastieren oder konkurrierende Erklärungen zu entkräften (vgl. @EisenhardtGraebner2007[S. 25-27]).

Der Forschungsprozess nach Yin gliedert sich in sechs aufeinander aufbauende Phasen, nämlich Plan, Design, Prepare, Collect, Analyze und Share, die den gesamten Ablauf von der ersten Konzeption bis zur abschließenden Kommunikation der Ergebnisse strukturieren.

*Plan*

In der Plan-Phase wird grundlegend geklärt, ob die Fallstudie als Forschungsmethode für das jeweilige Erkenntnisinteresse geeignet ist. Nach Yin spricht für ihren Einsatz, wenn die Forschungsfragen auf ein Wie oder Warum abzielen, der Forscher keinen Einfluss auf das untersuchte Geschehen nehmen kann und ein gegenwärtiges Phänomen im Mittelpunkt steht (vgl. @Yin2014[S. 3]). Der Formulierung der Forschungsfrage kommt in diesem Zusammenhang eine besondere Bedeutung zu, denn sie ist nicht nur inhaltlicher Ausgangspunkt, sondern entscheidet durch ihre Form als Wie- oder Warum-Frage maßgeblich darüber, ob die Fallstudie als Methode überhaupt in Betracht kommt (vgl. @Yin2014[S. 11]).

*Design*

Die Designphase verfolgt das Ziel, logische Inkonsistenzen im Forschungsaufbau zu vermeiden und sicherzustellen, dass die erhobenen Daten tatsächlich zur Beantwortung der Forschungsfrage beitragen. Yin zufolge umfasst ein vollständiges Fallstudiendesign fünf zentrale Komponenten, nämlich die Forschungsfragen, theoretische Annahmen, die zu untersuchende Einheit, die Logik der Verknüpfung von Daten und Annahmen sowie Kriterien zur Interpretation der Befunde (vgl. @Yin2014[S. 61]).

*Prepare*

Die Prepare-Phase dient der systematischen Vorbereitung der Datenerhebung und gliedert sich nach Yin in fünf Bereiche. Diese umfassen die persönlichen Fähigkeiten des Forschers, ein fallspezifisches Training, die Erstellung eines Studienprotokolls, die Auswahl geeigneter Fälle sowie eine vorgelagerte Pilotstudie. Anders als bei Experimenten oder standardisierten Befragungen gibt es bei der Fallstudienforschung kein festgelegtes Erhebungsverfahren, weshalb der Forscher während der gesamten Datenerhebung fortlaufend eigene Urteile treffen muss. Yin benennt dabei konkrete Anforderungen an den Forscher, der gezielt und präzise fragen, aktiv zuhören, flexibel auf unerwartete Entwicklungen reagieren, die theoretischen Vorannahmen kontinuierlich im Blick behalten und mögliche Verzerrungen bewusst reflektieren sollte (vgl. @Yin2014[S. 71f]). Zur Absicherung der Reliabilität empfiehlt Yin die Erstellung eines Fallstudienprotokolls, das vier Bestandteile umfasst, nämlich eine Übersicht über das Forschungsprojekt, eine Beschreibung des Datenerhebungsprozesses, einen Katalog analytischer Fragen als Orientierungshilfe für den Forscher während der Feldarbeit sowie einen Leitfaden für die abschließende Berichterstattung (vgl. @Yin2014[S. 84f]).

Ergänzend weist Yin darauf hin, dass die analytischen Fragen des Protokolls nicht mit den Interviewfragen verwechselt werden dürfen, da sie ausschließlich als Reflexionshilfe für den Forscher selbst konzipiert sind und nicht an die Befragten gerichtet werden (vgl. @Yin2014[S. 89f]). Im Anschluss daran folgt das Screening, das der finalen Fallauswahl unmittelbar vor Beginn der Datenerhebung dient (vgl. @Yin2014[S. 95]). Da als Untersuchungseinheit Wissensarbeitende bei SAP, die aktiv Large Language Models einsetzen, von Beginn an feststanden, war ein aufwändiges Auswahlverfahren nicht erforderlich. Darüber hinaus empfiehlt Yin die Durchführung einer Pilotstudie, die sich von einem klassischen Pretest insofern unterscheidet, als sie nicht nur das Erhebungsinstrument erprobt, sondern auch konzeptionelle Klärungen für das Gesamtdesign ermöglicht (vgl. @Yin2014[S. 96]). In der vorliegenden Arbeit wurde auf eine Pilotstudie verzichtet, da der Forscher als internes Mitglied der SAP-Organisation über einen kontinuierlichen Feldzugang verfügte, der diese konzeptionelle Funktion bereits erfüllte.

*Collect*

In der Collect-Phase erfolgt die eigentliche Datenerhebung, wobei Fallstudien grundsätzlich auf eine Vielzahl unterschiedlicher Datenquellen zurückgreifen können. Keine dieser Quellen ist den anderen dabei von vornherein überlegen. Stattdessen zeichnet eine qualitativ hochwertige Fallstudie gerade dadurch aus, dass sie möglichst viele verschiedene Quellen miteinander kombiniert und so eine breitere und belastbarere Evidenzbasis schafft. Zu den gängigsten Datenquellen zählen nach Yin Dokumentation, Archivdaten, Interviews, direkte Beobachtung, teilnehmende Beobachtung sowie physische Artefakte (vgl. @Yin2014[S. 106f]). In der vorliegenden Arbeit werden zwei dieser Quelltypen kombiniert, nämlich Experteninterviews als primäre Erhebungsmethode sowie wissenschaftliche und praxisorientierte Literatur als sekundäre Evidenzbasis. Weitere bei Yin genannte Quellen wie interne Dokumente, direkte Beobachtung oder Archivdaten konnten aus forschungspraktischen Gründen nicht einbezogen werden, da der Feldzugang auf die Durchführung von Interviews begrenzt war.

*Analyze*

Gegenstand der Analysephase ist die systematische Auswertung der erhobenen Belege, die kategorisiert, tabellarisch aufbereitet und zueinander in Beziehung gesetzt werden, um daraus fundierte Erkenntnisse abzuleiten (vgl. @Yin2014[S. 133]). Anders als bei quantitativen Methoden stehen dem Forscher dabei weder standardisierte Verfahren noch feste Formeln zur Verfügung, weshalb er frühzeitig eine eigene Analysestrategie entwickeln sollte, idealerweise bereits in der Designphase. Als Orientierungsrahmen benennt Yin vier allgemeine Strategien, wobei der Forscher wahlweise an theoretischen Propositionen anknüpfen, induktiv von den Daten ausgehen, eine deskriptive Fallbeschreibung erarbeiten oder plausible Alternativerklärungen systematisch prüfen kann (vgl. @Yin2014[S. 136f]). Aufbauend auf diesen Strategien stehen zudem fünf spezifische Analysetechniken zur Verfügung, nämlich Pattern Matching, Explanation Building, Time-Series Analysis, Logic Models sowie Cross-Case Synthesis (vgl. @Yin2014[S. 142]).

Im Kontext der vorliegenden Arbeit kommen zwei Analysetechniken zum Einsatz. Zum einen wird Pattern Matching als primäre Technik genutzt, da die in der Literaturanalyse erarbeiteten theoretischen Muster zu Veränderungen in Arbeitsprozessen und Kompetenzprofilen mit den empirischen Befunden der Experteninterviews abgeglichen werden. Stimmen die beobachteten Muster mit den theoretisch erwarteten überein, stärkt dies die interne Validität der Ergebnisse (vgl. @Yin2014[S. 143]). Ergänzend dazu wird Explanation Building eingesetzt, um auf Basis dieses Abgleichs schrittweise eine konsistente Erklärung dafür zu entwickeln, wie und unter welchen Bedingungen LLMs die Wissensarbeit bei SAP verändern. Die Erklärung entsteht dabei iterativ, indem eine theoretische Ausgangsthese mit den erhobenen Interviewdaten konfrontiert und in mehreren Schritten so lange verfeinert wird, bis ein stimmiges Gesamtbild vorliegt (vgl. @Yin2014[S. 147f]). Unabhängig von der gewählten Technik hebt Yin schließlich vier Qualitätsmerkmale einer guten Analyse hervor, nämlich die lückenlose Berücksichtigung aller erhobenen Belege, die aktive Auseinandersetzung mit konkurrierenden Erklärungsansätzen, die konsequente Fokussierung auf den zentralen Forschungsgegenstand sowie die reflektierte Nutzung des eigenen Expertenwissens (vgl. @Yin2014[S. 168f]).

*Share*

Als abschließender Schritt des Fallstudienforschungsprozesses umfasst die Share-Phase die Aufbereitung und Kommunikation der gewonnenen Erkenntnisse. Für wissenschaftliche Abschlussarbeiten bietet sich dabei die linear-analytische Struktur an, bei der die Darstellung von der Forschungsfrage über Methodik und Daten bis hin zu Befunden und Schlussfolgerungen logisch aufgebaut wird (vgl. @Yin2014[S. 188]). Als übergeordnetes Gütemerkmal gilt, dass der Bericht so viele Belege enthält, dass sich der Leser auf dieser Basis ein eigenes, unabhängiges Urteil über die präsentierten Befunde bilden kann (vgl. @Yin2014[S. 205]).

Grundsätzlich wären für diese Arbeit auch alternative Forschungsdesigns denkbar gewesen, etwa eine Mehrfachfallstudie oder ein quantitatives Umfragedesign. Dennoch erweist sich die Einzelfallstudie nach Yin als am besten geeignet, weil die Rollentransformation ein zeitgenössisches Phänomen darstellt, das nicht losgelöst von seinem organisationalen Kontext betrachtet werden kann, und weil eine quantitative Erhebung voraussetzen würde, dass die relevanten Variablen bereits bekannt sind. SAP erfüllt dabei Yins Kriterium eines Revelatory Case, da der Forscher als internes Mitglied der SAP-Organisation einen Feldzugang zu einem Phänomen besitzt, das externen Forschern bislang weitgehend verschlossen ist. Der reale Einsatz von Large Language Models in der Wissensarbeit eines Großunternehmens ist empirisch kaum dokumentiert, sodass bereits die deskriptiven Befunde einen eigenständigen Erkenntniswert besitzen (vgl. @Yin2014[S. 52]). Als Analyseeinheit werden dabei Wissensarbeitende bei SAP definiert, die im Rahmen ihrer beruflichen Tätigkeit aktiv Large Language Models einsetzen.

Die Kombination aus systematischer Literaturanalyse und Experteninterviews wurde dabei bewusst gewählt, weil weder eine reine Literaturanalyse noch ein alleiniges Interviewdesign das Erkenntnisinteresse dieser Arbeit vollständig erfüllen könnte. Eine reine Literaturanalyse hätte zwar einen fundierten theoretischen Überblick ermöglicht, aber keine Aussage darüber getroffen, ob die beschriebenen Veränderungen im konkreten Unternehmenskontext von SAP tatsächlich eintreten. Umgekehrt hätten Interviews ohne theoretische Fundierung keine Einordnung der Praxiserfahrungen in einen übergeordneten Forschungsstand erlaubt. Erst die Kombination beider Methoden ermöglicht es, theoretische Muster aus der Literatur zu identifizieren und ihre Gültigkeit im spezifischen Unternehmenskontext empirisch zu prüfen.

== Systematische Literaturanalyse

*Methodisches Vorgehen der Literaturanalyse nach Snyder*

Um für die Untersuchung der Wissensarbeit bei SAP eine valide und reproduzierbare Grundlage zu schaffen, folgt diese Arbeit dem methodischen Rahmen von @Snyder2019. Da im Rahmen dieser Arbeit festgestellt wurde, dass das Forschungsfeld der generativen Künstlichen Intelligenz durch eine hohe Entwicklungsgeschwindigkeit und ein breites fachübergreifendes Spektrum geprägt ist, eignet sich dieser Ansatz besonders, da er nicht auf rein quantitative Methoden beschränkt ist, sondern auch die gemeinsame Auswertung von Quellen aus unterschiedlichen Forschungsrichtungen ermöglicht (vgl. @Snyder2019[S. 334]). Das Vorgehen gliedert sich dabei in den vierphasigen Prozess aus Design, Durchführung, Analyse und Verschriftlichung (vgl. @Snyder2019[S. 336-337]).

In der ersten Phase, dem Review-Design, wird die methodische Ausrichtung festgelegt. Aufgrund der beschriebenen Aktualitätsproblematik und der Notwendigkeit, verschiedene Perspektiven zu vereinen, wird ein integrativer Review-Ansatz gewählt. Dieser eignet sich nach Snyder besonders für neue Themenbereiche, bei denen noch kein etabliertes theoretisches Modell existiert und das Ziel darin besteht, erste Zusammenhänge und Muster zu erkennen, anstatt bestehende Ansätze lediglich zu bestätigen (vgl. @Snyder2019[S. 336]). Entsprechend den Vorgaben von Snyder wurden in dieser Phase zunächst die Forschungsfragen festgelegt, die als Grundlage für die gesamte Suche und Analyse dienen (vgl. @Snyder2019[S. 336]). Sie adressieren dabei sowohl theoretische Potenziale als auch praktische Realitäten des KI-Einsatzes bei SAP. Darüber hinaus wurde die Suchstrategie definiert: Die wissenschaftliche Suche erfolgte in den Datenbanken Google Scholar, arXiv, ResearchGate sowie dem Bibliothekskatalog der DHBW Ravensburg mit den Suchbegriffen „how AI shapes and evolves knowledge work", „generative AI productivity" sowie „LLM in knowledge work". Praxisorientierte Quellen wie Beratungsstudien wurden über gezielte KI-gestützte Recherche identifiziert und verifiziert. Da eine Literatursuche in der Regel eine große Anzahl an Treffern liefert, wurden auf Basis der Forschungsfrage zudem konkrete Ein- und Ausschlusskriterien festgelegt, anhand derer die tatsächlich relevanten Quellen identifiziert werden sollten (vgl. @Snyder2019[S. 337]). Snyder betont dabei, dass alle Ein- und Ausschlussentscheidungen explizit begründet sein müssen, um die Transparenz und die Qualität des Reviews sicherzustellen (vgl. @Snyder2019[S. 337–338]). Dies wird in dieser Arbeit durch die kritische Würdigung der grauen Literatur realisiert.

In der zweiten Phase der Durchführung wurde die eigentliche Literatursuche anhand der in Phase 1 festgelegten Strategie umgesetzt. Snyder empfiehlt, die Suchbegriffe und Auswahlkriterien zunächst an einer kleineren Auswahl zu testen und den Prozess bei Bedarf anzupassen, bevor die vollständige Suche durchgeführt wird (vgl. @Snyder2019[S. 337]). Entsprechend diesem Vorgehen wurden die Suchbegriffe in einem ersten Schritt erprobt und verfeinert. Die Quellenauswahl erfolgte anschließend in zwei Stufen: Zunächst wurden die Treffer anhand von Titel und Abstract auf ihre Relevanz geprüft, bevor die verbliebenen Quellen im Volltext gelesen und abschließend bewertet wurden. Snyder empfiehlt zudem den Einsatz von zwei Reviewern, um die Qualität und Reliabilität der Quellenauswahl zu sichern (vgl. @Snyder2019[S. 337]). Da die vorliegende Arbeit von einem einzelnen Autor verfasst wird, konnte diesem Vorgehen nicht entsprochen werden; diesem Umstand wird durch die explizite Dokumentation der Ein- und Ausschlusskriterien begegnet. Alle Entscheidungen wurden dabei auf Basis der in Phase 1 definierten Kriterien getroffen und sind durch die kritische Würdigung der Quellenkategorien nachvollziehbar dokumentiert (vgl. @Snyder2019[S. 337]).

Nach der Identifikation der relevanten Quellen erfolgt in der dritten Phase die Analyse. Snyder betont, dass nach der Festlegung der endgültigen Quellen ein einheitliches Vorgehen zur Informationsentnahme angewendet werden sollte, um Qualität und Verlässlichkeit der Auswertung sicherzustellen (vgl. @Snyder2019[S. 337]). In dieser Arbeit wurden aus den ausgewählten Quellen relevante Informationen in Form von Befunden, Einschätzungen und thematischen Schwerpunkten entnommen. Die Analyse erfolgt dabei nicht rein autorenorientiert, sondern konzeptzentriert: Themen wie „Veränderung von Arbeitsprozessen", „Kompetenzwandel durch KI" oder „Chancen und Risiken des KI-Einsatzes" wurden über die verschiedenen Quellenkategorien hinweg extrahiert und miteinander verglichen. Da das Ziel dieser Arbeit nicht die statistische Auswertung von Effektgrößen, sondern die Entwicklung eines inhaltlichen Überblicks ist, wurde eine für integrative Reviews geeignete Analysetechnik gewählt (vgl. @Snyder2019[S. 337]).

In der abschließenden Phase der Verschriftlichung werden die Ergebnisse so aufbereitet, dass Motivation, Vorgehen und Erkenntnisse des Reviews klar und nachvollziehbar kommuniziert werden (vgl. @Snyder2019[S. 337]). Snyder verweist dabei auf anerkannte Richtlinien zur Berichterstattung von Literaturreviews, darunter die Leitlinien für integrative Reviews nach Torraco (Torraco, 2005, zitiert nach @Snyder2019[S. 337]). Unabhängig vom gewählten Ansatz wird erwartet, dass der gesamte Prozess von der Planung über die Suche bis hin zur Analyse transparent beschrieben wird, damit der Leser die Qualität und Verlässlichkeit der Ergebnisse einschätzen kann (vgl. @Snyder2019[S. 337]). In dieser Arbeit wird diesem Anspruch durch die detaillierte Beschreibung der vier Phasen in diesem Kapitel entsprochen. Snyder beschreibt, dass der Beitrag eines Reviews verschiedene Formen annehmen kann, etwa eine konzeptionelle Aufarbeitung eines Forschungsfelds (vgl. @Snyder2019[S. 337]). In dieser Arbeit besteht der Beitrag darin, einen strukturierten Überblick über den aktuellen Wissensstand zur Veränderung der Wissensarbeit durch KI-Textgenerierung zu schaffen.

*Zielsetzung und Vorgehen*

Die vorliegende Arbeit untersucht, wie KI-Textgenerierung mittels Large Language Models Arbeitsprozesse und Kompetenzprofile in der Wissensarbeit bei SAP verändert sowie welche Chancen und Risiken sich daraus ergeben. Da es sich um ein Forschungsfeld handelt, in dem im Rahmen dieser Arbeit festgestellt wurde, dass die akademische Literatur der technologischen Entwicklung teils mit zeitlichem Verzug folgt, wurde die Literaturanalyse bewusst mehrstufig angelegt: Sie kombiniert drei Quellenkategorien, die zwei unterschiedliche Funktionen erfüllen, nämlich die theoretisch-methodische Fundierung durch wissenschaftliche Studien einerseits sowie die Abbildung empirischer Aktualität und Praxisrelevanz durch Berater- und Fachpressequellen andererseits.

Die einbezogene Literatur lässt sich dabei in drei Kategorien unterteilen. Wissenschaftliche Literatur in Form von peer-reviewten Studien und Working Papern bildet die theoretische Basis der Arbeit und liefert methodisch abgesicherte Erkenntnisse zu Automatisierungspotenzialen und Produktivitätseffekten. Beratungsstudien (graue Literatur) großer Institute liefern ergänzend aktuelle, breit angelegte empirische Daten zu Skill-Wandel oder Adoptionsraten, die wissenschaftlich oft noch nicht verfügbar sind. Fachpresse und Praxisbeiträge runden das Bild punktuell ab, indem sie die praktische Rezeption der Entwicklungen in Unternehmen abbilden. Da geeignete Fachpressebeiträge im Zuge der Recherche nur vereinzelt identifiziert werden konnten, stützt sich die Analyse in diesem Bereich überwiegend auf Beratungsstudien, die eine vergleichbare Funktion erfüllen.

Zur Sicherung der Quellenqualität werden spezifische Auswahlkriterien angelegt. Neben einer strikten Aktualität (Fokus auf 2023–2026) wird bei Beratungsstudien die Transparenz der Methodik (Stichprobengröße, Erhebungszeitraum) geprüft. Um eine einseitige Darstellung zu vermeiden, wird auf Ausgewogenheit geachtet, indem auch kritische Gegenpositionen zum KI-Einsatz in Unternehmen einbezogen werden. Reine Meinungsbeiträge ohne empirische Grundlage werden ausgeschlossen.

Diese einbezogenen Beratungsquellen stellen keine peer-reviewte Literatur im engeren Sinne dar und sind entsprechend kritisch zu würdigen. Insbesondere bei Studien von Unternehmensberatungen ist ein potenzieller Interessenkonflikt zu berücksichtigen, da diese Institute selbst kommerzielle KI-Transformationsleistungen anbieten. Dieser methodischen Einschränkung wird dadurch begegnet, dass Beratungsquellen stets in Verbindung mit wissenschaftlichen Quellen herangezogen werden und ihre empirischen Befunde nur dort als eigenständige Belege gelten, wo vergleichbare wissenschaftliche Daten aufgrund der Aktualität des Forschungsfelds noch nicht verfügbar sind.

== Experteninterviews

Als eine der zentralen Methoden qualitativer Forschung findet das Experteninterview in unterschiedlichen Forschungsfeldern Anwendung und kann dabei sowohl als eigenständiges Instrument als auch in Kombination mit weiteren Forschungsmethoden eingesetzt werden (vgl. @Burger2011[S. 127]). Im Mittelpunkt steht die gezielte Erschließung des Fachwissens ausgewählter Experten, um auf dieser Basis wissenschaftlich fundierte Erkenntnisse zu gewinnen (vgl. @Bogner2014[S. 17]).

Das Interview stellt in seiner grundlegenden Form eine mündliche Befragung dar (vgl. @RennerJacob2020[S. 1]). Befragungen lassen sich dabei generell in quantitative und qualitative Verfahren unterteilen (vgl. @FantapieAltobelli2017[S. 55, 357]). Leitfadengestützte Experteninterviews zählen zu den qualitativen Methoden der Datenerhebung. Da die gewonnenen Daten im Anschluss unmittelbar weiterverarbeitet werden, ist bei der Durchführung besondere Sorgfalt geboten (vgl. @BaurBlasius2022[S. 875]).

Qualitative Befragungen unterscheiden sich von quantitativen Verfahren insbesondere durch ihren kleineren Umfang. Anstelle standardisierter Fragen stehen individualisierte Fragen im Vordergrund, die auf Informationen abzielen, die für Außenstehende nicht ohne Weiteres zugänglich sind (vgl. @FantapieAltobelli2017[S. 357]). Ein Leitfadeninterview eignet sich insbesondere dann, wenn der Interviewer mit dem Thema vertraut ist oder es gezielt eingrenzen kann. In beiden Fällen ermöglichen vorab formulierte Fragen eine strukturierte Gesprächsführung (vgl. @Porst2015[S. 95]). Das Experteninterview stellt eine besondere Form des Leitfadeninterviews dar, bei der der Fokus auf dem Fachwissen und der Praxiserfahrung der befragten Person liegt. Dies erlaubt es, zielgerichtete und komplexere Fragestellungen zu adressieren, die ausschließlich durch den Sachverstand eines Experten beantwortet werden können (vgl. @BaurBlasius2022[S. 888–889]).

Nach Renner und Jacob lassen sich Interviews grundsätzlich in hoch standardisierte, unstandardisierte sowie teilstandardisierte bzw. halbstrukturierte Formen unterteilen, wobei letztere die Vorteile beider Extremformen vereint, indem sie sich an einem Leitfaden orientiert, gleichzeitig aber Raum für ergänzende Fragen lässt (vgl. @RennerJacob2020[S. 13–17]).

Der Leitfaden strukturiert den Ablauf aller Gespräche und ermöglicht so eine einheitliche Gesprächsführung. Er kann Erzählaufforderungen, vorformulierte Fragen sowie Stichpunkte enthalten und bei Bedarf auch Stimuli wie Bilder oder Geschichten einbeziehen. Dabei wird stets eine Balance zwischen Offenheit und Strukturiertheit angestrebt. Bei der Erstellung empfiehlt sich ein dreistufiges Vorgehen, bei dem zunächst möglichst offene Fragen gestellt werden, die dem Befragten freie Antworten ermöglichen und so alle relevanten Informationen erschließen. Anschließend können gezielte Nachfragen zu Themen gestellt werden, die bisher unbeantwortet oder unzureichend behandelt wurden. Abschließend werden vorformulierte Fragen in einer logischen Reihenfolge an den Interviewten gerichtet (vgl. @BaurBlasius2022[S. 881–883]).

Als Experten können Personen herangezogen werden, die über ein überdurchschnittliches, umfangreiches Wissen oder eine besondere fachliche Tiefe in einem bestimmten Bereich verfügen. Dies umfasst sowohl Insiderwissen, das für Außenstehende nur schwer zugänglich ist, als auch einen allgemein vertieften Wissensstand im jeweiligen Fachgebiet. Expertenwissen beschränkt sich dabei nicht auf die Berufswelt, sodass auch Personen, die sich ein spezifisches Thema eigenständig erschlossen oder darin besondere Fähigkeiten entwickelt haben, in diesen Bereichen als Experten gelten können. Im Mittelpunkt der Interviews steht die fachliche Expertise der Befragten und nicht ihre persönliche Lebenssituation. Den Interviewpartnern wird dabei verdeutlicht, welche bedeutsame Rolle ihr Wissen für die Beantwortung der Forschungsfrage einnimmt (vgl. @BaurBlasius2022[S. 887–888]).

In der vorliegenden Arbeit wurden vier Wissensarbeitende bei SAP als Experten befragt, die Large Language Models aktiv und regelmäßig in ihren beruflichen Alltag integriert haben. Drei der Befragten sind in einer internen Beratungseinheit von SAP tätig und decken beratungs- sowie projektnahe Tätigkeitsfelder ab, während die vierte Person als Senior Developer im Bereich S/4HANA Cloud eine technische Entwicklungsperspektive einbringt. Ihre Expertise ergibt sich damit nicht aus einer formalen Zertifizierung, sondern aus dem praktisch aufgebauten Erfahrungswissen im konkreten Einsatz von KI-Tools im Unternehmenskontext. Die Durchführung und Auswertung der Interviews werden in Kapitel 5 dargestellt.

