= Experteninterviews, Diskussion und Handlungsempfehlungen

Das folgende Kapitel ergänzt die Literaturanalyse aus Kapitel 4 um eine empirische Perspektive und verfolgt dabei drei aufeinander aufbauende Ziele. Abschnitt 5.1 stellt zunächst die Durchführung der Experteninterviews dar und wertet die Aussagen der vier befragten Wissensarbeitenden bei SAP thematisch aus. Darauf aufbauend gleicht Abschnitt 5.2 die Interviewergebnisse mit den theoretischen Befunden aus Kapitel 4 ab, um zu prüfen, inwiefern die Literatur durch die Praxisperspektiven bestätigt, ergänzt oder herausgefordert wird. Abschnitt 5.3 benennt anschließend die methodischen Limitationen der Untersuchung, bevor Abschnitt 5.4 auf Basis der gewonnenen Erkenntnisse konkrete Handlungsempfehlungen für SAP ableitet.

== Durchführung und Auswertung der Interviews

Zur Beantwortung der Forschungsfrage wurden ergänzend zur Literaturanalyse leitfadengestützte Experteninterviews durchgeführt. Als Grundlage für die Gespräche diente ein Interviewleitfaden, der im Rahmen der Vorbereitung entwickelt wurde und im Anhang in Abbildung 1 eingesehen werden kann. Parallel dazu wurden geeignete Interviewpartner aus dem Unternehmensumfeld von SAP identifiziert, kontaktiert und die Gesprächstermine koordiniert.

*Durchführung der Experteninterviews*

Im Vorfeld jedes Interviews wurden die Teilnehmenden über die Zielsetzung und den Kontext der Arbeit informiert, um einen gemeinsamen Ausgangspunkt zu schaffen. Die Interviews fanden jeweils unabhängig voneinander in Form von Videokonferenzen statt und dauerten durchschnittlich ca. 30 Minuten. Um einen natürlichen Gesprächsfluss zu ermöglichen, wurde die Reihenfolge der Fragen flexibel gehandhabt. Mit ausdrücklicher Zustimmung der Teilnehmenden wurden die Gespräche aufgezeichnet, sodass eine sorgfältige Auswertung im Nachgang möglich war. Darüber hinaus wurden die Teilnehmenden zu Beginn des Gesprächs darauf hingewiesen, dass ihre Aussagen sowie ihre Person vollständig anonymisiert behandelt werden.

*Auswertung der Experteninterviews*

Im Folgenden werden die Aussagen der vier Interviewpartner thematisch verglichen, um Gemeinsamkeiten und Unterschiede systematisch herauszuarbeiten.

Person A ist seit ca. vier bis fünf Jahren bei PCG tätig und arbeitet als Projektmanagerin in einem internen Transformationsprojekt, das die Neugestaltung zweier Support-Einheiten umfasst. Person B ist seit ca. 15 Jahren bei PCG in verschiedenen Rollen aktiv und beschäftigt sich aktuell mit Entitlement Checks für Partnerprodukte, Customer Support Profiles sowie internen KI-Projekten. Person C ist ebenfalls bei PCG tätig, seit 20 Jahren bei SAP und aktuell in einem internen Transformationsprojekt tätig, das Kundenkommunikation auf Kanal-, Technologie- und Geschäftsprozessebene neu gestaltet. Person D kommt demgegenüber aus einem anderen Tätigkeitsfeld und ist Senior Developer in einer Entwicklungsabteilung bei SAP und seit 2019 nach Abschluss des DHBW-Studiums in der Abteilung tätig. Sein Schwerpunkt liegt auf der Softwareentwicklung sowie der Betreuung von Studierenden, insbesondere im Bereich Performance-KPIs für Apps. Damit repräsentieren Personen A, B und C eher beratungs- und projektnahe Wissensarbeit, während Person D die Perspektive technischer Entwicklungsarbeit einbringt.

Alle vier Interviewpartner nutzen KI-Tools regelmäßig in ihrem Arbeitsalltag. So gibt Person D an, die Tools täglich zu verwenden, nachdem die Nutzung durch einen internen Aufruf angestoßen wurde. Auch Personen A, B und C berichten von einer regelmäßigen, teils täglichen Nutzung. Hinsichtlich der Einsatzfelder unterscheiden sich die Antworten entsprechend der jeweiligen Tätigkeitsschwerpunkte. Person A verwendet primär EKX für Präsentationen sowie MS Copilot für E-Mail-Formulierungen und Texte und nutzt darüber hinaus Teams Premium für automatische Meeting-Summaries. Person B setzt KI demgegenüber vor allem für PM-Aufgaben wie das Aufsetzen von Projekten und Work-Breakdown-Structures, als Sparring-Partner bei Präsentationen sowie als Lern-Tutor bei neuen Themen ein. Person C nutzt Claude und EKX wiederum vor allem zur Analyse größerer Datenmengen und Dokumente sowie zur Zusammenfassung umfangreicher Compliance-Texte. Person D schließlich konzentriert sich auf Code-Generierung und Dokumentation, einschließlich der Erstellung technischer und nutzerorientierter Anleitungen.

Bei der Frage nach Hemmfaktoren zeigen sich sowohl Gemeinsamkeiten als auch Unterschiede. Personen A und C berichten, dass sie persönlich kaum durch externe Faktoren gehemmt werden. Für Kolleginnen und Kollegen identifizieren jedoch alle Befragten ähnliche Muster, nämlich initiale Skepsis gegenüber neuen Technologien, fehlendes Vertrauen in die Zuverlässigkeit der Tools sowie mangelnde Kenntnis über sinnvolle Anwendungsfälle. Person D beschreibt dieses Muster als typisches Gewohnheitsverhalten, da Kolleginnen und Kollegen auf disruptive Technologien wie KI zunächst skeptisch reagierten. Ergänzend dazu weist Person B darauf hin, dass für fortgeschrittene Anwendungen wie den Aufbau von Agenten noch geeignete Schulungsangebote fehlten.

Alle vier Personen beschreiben eine Veränderung ihrer Arbeitspraxis durch KI, die in ihrer Ausprägung jedoch variiert. Person A berichtet, dass sie administrative PM-Aufgaben zunehmend an KI delegiert und dadurch mehr Zeit für strategisch-inhaltliche Themen gewinnt. Person B hebt ergänzend hervor, dass die gleichzeitige Betreuung mehrerer Projekte einfacher geworden sei, weist allerdings auch auf den Prüfaufwand für KI-generierte Ergebnisse hin, der die Zeitersparnis teilweise kompensiere. Person C schätzt die persönliche Geschwindigkeitssteigerung im aktuellen Strategie-Projekt auf ca. 10 %, verweist jedoch auf deutlich höhere Potenziale in Projekten mit Massendaten. Person D beschreibt demgegenüber eine strukturelle Veränderung, da das Team angehalten sei, bei jeder Problemstellung aktiv zu prüfen, ob KI-Einsatz sinnvoll sei. Zudem werde Dokumentation heute standardmäßig KI-unterstützt erstellt, was auch die Umstellung von Word-Dateien auf das Markdown-Format erfordere.

Bei der Einschätzung, welche Aufgaben für KI geeignet sind, zeigen sich sowohl übereinstimmende als auch spezifische Kriterien. Personen A und B stimmen darin überein, dass Formulierungsaufgaben, Texterstellung und Zusammenfassungen besonders gut geeignet sind, wobei Person A davon explizit Aufgaben mit empathischer oder teamdynamischer Komponente abgrenzt, etwa individuelle Workshop-Agenden. Person C stellt hingegen den Datenschutz als primären Eignungsfilter heraus, da vor jeder inhaltlichen Abwägung geprüft werden müsse, ob personenbezogene oder vertrauliche Daten betroffen seien. Person D beschreibt Code-Analyse als besonders geeigneten Anwendungsfall, benennt jedoch gleichzeitig auch eine klare Grenze, denn sobald viele voneinander abhängige Klassen und Objekte im Spiel seien, verliere die KI den Kontextüberblick.

Alle Befragten haben konkrete Erfahrungen mit fehlerhaften KI-Ausgaben gemacht und beschreiben einen ähnlichen Umgang damit, nämlich kritisches Hinterfragen und eigenständige Verifikation. Person A schildert dabei einen Fall, in dem Copilot durch einen Transkriptionsfehler wiederholt ein nicht existierendes Projekt erfand und sie das gesamte 90-minütige Meeting abhören musste, um die Fehlerquelle zu finden. In ähnlicher Weise berichtet Person D von einem Kollegen, dem die KI zu einer ABAP-Syntax-Frage eine klare, aber faktisch falsche Antwort gab, die der offiziellen Dokumentation widersprach. Demgegenüber beschreiben Personen B und C strukturiertere Gegenstrategien. So hat Person B einen Kontext-Prompt entwickelt, der die KI zu Rückfragen und Selbstkorrektur anhält, während Person C empfiehlt, bei numerischen Auswertungen explizit nachrechnen zu lassen, da in fast der Hälfte der Fälle leichte Abweichungen in der zweiten Antwort auftreten.

Im Bereich Datenschutz zeigen alle vier Personen ein ausgeprägtes Bewusstsein, das sich in konkreten Verhaltensregeln niederschlägt. Übereinstimmend berichten alle, dass keine personenbezogenen Daten an KI-Tools weitergegeben werden. Personen B und C betonen darüber hinaus die Bedeutung von Vertraulichkeitsstufen und des Need-to-Know-Prinzips. Person C kritisiert dabei, dass klare Vorgaben oft nur in Wiki-Artikeln hinterlegt seien und nicht direkt am Eingabefeld der Tools erscheinen. Person D hebt ergänzend hervor, dass bei jedem KI-unterstützten Entwicklungsschritt eine menschliche Prüfinstanz im Sinne eines Human in the Loop obligatorisch sei.

Bei der Frage nach veränderten Kompetenzen und dem Risiko des Verlernens zeigen sich deutliche Unterschiede. Während Personen B und D das Verlernrisiko klar benennen, berichten Personen A und C kaum davon betroffen zu sein. Person D gibt dabei offen zu, nicht mehr zu wissen, wann er zuletzt eigenständig ABAP-Code entwickelt habe, da der gedankliche Entwicklungsprozess zunehmend durch die KI übernommen werde. Person B beschreibt demgegenüber, dass die Gefahr des Verlernens durch aktive Evaluation von KI-Ergebnissen teilweise kompensiert werden könne. Person A berichtet hingegen, dass KI-Nutzung bei ihr sogar den Lerneffekt bei unbekannten Themen fördere, während Person C das Risiko für ihre aktuelle Arbeitspraxis ebenfalls verneint. Als neue Schlüsselkompetenz nennen Personen A und B übereinstimmend die Fähigkeit zum gezielten Prompting sowie zur kritischen Evaluation von KI-Outputs.

Hinsichtlich der Vorteile stimmen alle Befragten darin überein, dass Zeitersparnis und Qualitätssteigerung bei analytischen und dokumentarischen Aufgaben zentrale Stärken von KI-Tools sind. Person B ergänzt dabei aus organisationaler Perspektive, dass KI auch aus Kostensicht relevant sei, da sie unter Umständen Personal ersetzen könne. Sowohl Person B als auch Person D weisen zudem auf eine wachsende Spreizung zwischen KI-affinen und KI-ablehnenden Mitarbeitenden hin, die zu Spannungen in Teams führen könne. Bei den Empfehlungen für SAP zeigen sich mehrere Überschneidungen. So fordern Personen A und C eine bessere Sichtbarkeit von Datenschutzregeln, insbesondere direkt am Eingabefeld der Tools. Person B empfiehlt darüber hinaus, Mitarbeitende gezielt in der strukturierten Evaluation von KI-Ergebnissen zu schulen und die dafür notwendigen Kapazitäten einzuplanen. Person D betont abschließend, dass Token-Limits und KI-Budgets sinnvoll gestaltet werden müssten und die menschliche Kontrollinstanz in KI-getriebenen Prozessen dauerhaft verankert werden solle.

== Diskussion der Ergebnisse im Abgleich mit der Literatur

Die Ergebnisse der Experteninterviews werden im Folgenden den Befunden der Literaturanalyse aus Kapitel 4 gegenübergestellt. Ziel ist es, zu prüfen, inwiefern die in der Literatur beschriebenen Veränderungen in Arbeitsprozessen, Kompetenzprofilen sowie Chancen und Risiken durch die Praxiserfahrungen der befragten Wissensarbeitenden bei SAP bestätigt, ergänzt oder herausgefordert werden.

*Veränderungen von Arbeitsprozessen*

Die Literaturanalyse zeigt, dass KI-Textgenerierung Arbeitsprozesse vor allem durch eine Verlagerung von ausführenden hin zu steuernden und überwachenden Tätigkeiten verändert, ohne dabei Arbeitsplätze vollständig zu ersetzen. Dieses Bild spiegelt sich in den Interviews deutlich wider. Alle vier befragten Personen beschreiben, dass KI-Tools routineorientierte Aufgaben wie Texterstellung, Dokumentation oder Codeanalyse übernehmen, während sie selbst zunehmend in prüfende, bewertende oder steuernde Rollen wechseln. Person A berichtet, dass sie administrative Aufgaben an KI delegiert und dadurch mehr Kapazität für strategisch-inhaltliche Tätigkeiten gewinnt, was die in der Literatur beschriebene Entlastung von Routineaufgaben unmittelbar bestätigt. In ähnlicher Weise beschreibt Person D, dass das Team angehalten sei, bei jeder Problemstellung aktiv zu prüfen, ob KI-Einsatz sinnvoll sei, was die von McKinsey und BCG beschriebene Steuerungsrolle des Menschen in KI-gestützten Prozessen in der Praxis abbildet.

Auch die in der Literatur beschriebene Verschiebung des Qualitätsmaßstabs von Effizienz hin zur Ergebnisqualität findet in den Interviews eine klare Entsprechung. Alle Befragten betonen, dass KI-Ausgaben stets kritisch geprüft werden müssen und nicht unbesehen übernommen werden können. Person D schildert dabei exemplarisch, dass unkritisch übernommener KI-Code langfristig kaum wartbar wäre, was den in der Literatur beschriebenen nicht-deterministischen Charakter von ML-Systemen als praktisches Risiko bestätigt. Person B ergänzt, dass der Prüfaufwand für KI-generierte Ergebnisse die Zeitersparnis teilweise kompensiere, was das von der BCG-Studie beschriebene Spannungsverhältnis zwischen Effizienz und Verantwortlichkeit in der Praxis widerspiegelt.

*Veränderungen der Kompetenzprofile*

Die Literatur identifiziert KI-Kompetenz und kritisches Denken als zentrale neue Anforderungen an Wissensarbeitende. Dieser Befund wird durch alle vier Interviews gestützt. Personen A und B benennen gezieltes Prompting sowie die kritische Evaluation von KI-Outputs als die wichtigsten neu entstandenen Fähigkeiten in ihrer Arbeitspraxis. Darüber hinaus bestätigen die Interviews die von der Literatur beschriebene Notwendigkeit kontinuierlichen Lernens. Person B berichtet, dass die Fähigkeit zur strukturierten Evaluation von KI-Ergebnissen im Team noch aktiv entwickelt werden müsse, während Person D die Umstellung von Word-Dateien auf Markdown als konkrete neue technische Anforderung beschreibt, die zunächst eine Lernhürde darstellte.

Besonders deutlich zeigt sich in den Interviews die Relevanz von Datenschutz- und Sicherheitskompetenz, die die Literatur als wachsende Querschnittsanforderung beschreibt. Person C hebt hervor, dass Datenschutz bei ihr als primärer Filter vor jeder inhaltlichen Eignung von KI-Aufgaben steht, und kritisiert, dass klare Vorgaben in vielen Tools nicht direkt am Eingabefeld erscheinen, sondern nur in internen Wiki-Artikeln hinterlegt sind. Damit bestätigt sie nicht nur den in der Literatur beschriebenen Kompetenzaufbau als Notwendigkeit, sondern weist auch auf eine strukturelle Lücke hin, die in der Literatur so nicht explizit thematisiert wird.

Das in der Literatur beschriebene Risiko des Cognitive Offloading, also der Schwächung kognitiver Fähigkeiten durch zunehmende Delegation an KI, findet in den Interviews eine differenzierte Bestätigung. Person D beschreibt offen, dass der gedankliche Entwicklungsprozess beim eigenständigen Coden zunehmend durch die KI übernommen werde und das Verlernrisiko real sei. Person B bestätigt das grundsätzliche Risiko, sieht in der aktiven Auseinandersetzung mit KI-Ergebnissen jedoch einen möglichen Ausgleich. Personen A und C hingegen berichten nicht von einem Verlerneffekt, was darauf hindeutet, dass das Risiko stark von der Art der Tätigkeit und dem Grad der KI-Nutzung abhängt.

Dieser Befund führt zu einer eigenständigen Schlussfolgerung, die so in der gesichteten Literatur nicht explizit formuliert wird. Das Verlernrisiko durch KI-Nutzung ist demnach nicht generell vorhanden oder abwesend, sondern ausgeprägt tätigkeitsabhängig. Es tritt besonders dann auf, wenn Wissensarbeitende KI für strukturierte, wiederholbare kognitive Kernprozesse ihrer Rolle einsetzen, wie etwa das eigenständige Entwickeln von Code. In projektnaher oder beratender Wissensarbeit hingegen, wo Tätigkeiten ohnehin stärker durch Kontexturteil, Kommunikation und situative Entscheidungen geprägt sind, scheint das Risiko deutlich geringer ausgeprägt zu sein. Für Organisationen wie SAP folgt daraus, dass Maßnahmen gegen das Verlernrisiko nicht pauschal für alle Mitarbeitenden gelten sollten, sondern gezielt auf jene Rollen ausgerichtet werden müssen, in denen KI strukturierte Kernkompetenzen ersetzt statt ergänzt.

*Chancen und Risiken*

Die in der Literatur beschriebene zentrale Chance der Entlastung von Routineaufgaben wird durch alle vier Interviews bestätigt. Besonders prägnant zeigt sich dies bei Person C, die bei der Analyse umfangreicher Compliance-Dokumente deutliche Zeitersparnisse berichtet, sowie bei Person D, dem die KI bei der Zusammenfassung langer Dokumente erhebliche Kapazitäten freisetzt. Ergänzend dazu beschreibt Person B, dass sich die gleichzeitige Betreuung mehrerer Projekte durch KI-Unterstützung deutlich vereinfacht habe, was die in der Literatur beschriebene Aufwertung strategischer Tätigkeiten durch KI in der Praxis belegt.

Das in der Literatur als zentrales Risiko beschriebene Fehlentscheidungen durch unkritische KI-Nutzung wird durch alle Interviewpartner aus eigener Erfahrung bekräftigt. So schildert Person A, wie Copilot durch eine Fehlerquelle im Transkript ein nicht existierendes Projekt erfand und den gesamten Prüfaufwand erhöhte, während Person D beschreibt, wie die KI zu einer ABAP-Syntax-Frage eine klare, aber faktisch falsche Antwort gab. Beide Fälle veranschaulichen, dass die in der Literatur beschriebene kontinuierliche menschliche Validierung nicht nur theoretisch notwendig, sondern in der Praxis unerlässlich ist.

Das Risiko einer wachsenden Qualifikationslücke, das die Literatur vor allem im Hinblick auf unterschiedliche Adoptionsgeschwindigkeiten beschreibt, tritt in den Interviews in Form eines konkreten Teamphänomens zutage. Sowohl Person B als auch Person D berichten von einer zunehmenden Spreizung zwischen KI-affinen und KI-ablehnenden Kolleginnen und Kollegen, die zu Ungleichgewichten in Teams führen könne. Darüber hinaus ergänzen die Interviews einen Aspekt, der in der Literatur weniger prominent behandelt wird, nämlich die Frage der Token-Kosten und KI-Budgets. Person D sowie Person B weisen darauf hin, dass ungleiche Nutzungslimits zwischen Rollen eine neue Form der Chancenungleichheit schaffen können, die Organisationen aktiv adressieren müssen.

Insgesamt zeigt der Abgleich, dass die in der Literatur beschriebenen Veränderungen in Arbeitsprozessen, Kompetenzanforderungen sowie Chancen und Risiken durch die Interviewergebnisse in weiten Teilen bestätigt werden. Gleichzeitig ergänzen die Praxisperspektiven die theoretischen Befunde an mehreren Stellen, insbesondere hinsichtlich der strukturellen Datenschutzlücken in Tool-Oberflächen, der rollenabhängigen Ausprägung des Verlernrisikos sowie der bisher wenig diskutierten Frage der KI-Budgetverteilung als organisationale Gerechtigkeitsfrage.

Aus dem Abgleich lassen sich dabei drei eigenständige Erkenntnisse ableiten, die so in der gesichteten Literatur nicht explizit formuliert werden. Erstens ist das Verlernrisiko durch KI-Nutzung nicht pauschal vorhanden oder abwesend, sondern abhängig davon, ob KI strukturierte kognitive Kernprozesse einer Rolle ersetzt oder lediglich ergänzt. Zweitens besteht eine strukturelle Datenschutzlücke nicht nur auf der Kompetenzebene der Mitarbeitenden, sondern auf der Gestaltungsebene der Tool-Oberflächen selbst, da Datenschutzhinweise dort häufig nicht sichtbar verankert sind. Drittens eröffnet die ungleiche Verteilung von KI-Nutzungsbudgets zwischen Rollen eine neue Dimension organisationaler Chancenungleichheit, die in der bisherigen Forschung zu KI und Wissensarbeit kaum thematisiert wird. Diese drei Erkenntnisse stellen den empirischen Eigenbeitrag der vorliegenden Arbeit dar und können als Ausgangspunkt für weiterführende Untersuchungen dienen.

== Limitationen der Untersuchung

Die vorliegende Arbeit weist eine Reihe von Einschränkungen auf, die bei der Interpretation der Ergebnisse berücksichtigt werden müssen.

Eine erste Limitation ergibt sich aus dem gewählten Forschungsdesign als Einzelfallstudie nach Yin. Wie in Kapitel 3 dargelegt, wurde SAP als Revelatory Case ausgewählt, da der Forscher als internes Mitglied der Organisation einen Feldzugang besitzt, der externen Forschern weitgehend verschlossen ist. Gleichzeitig schränkt diese Entscheidung die Übertragbarkeit der Ergebnisse auf andere Unternehmen und Branchen erheblich ein. Da SAP im Vergleich zu vielen anderen Unternehmen eine fortgeschrittene LLM-Adoption aufweist, lassen sich Aussagen über die Veränderung von Wissensarbeit durch KI in Unternehmen mit geringerer Adoptionsreife, anderen Organisationsstrukturen oder anderen regulatorischen Rahmenbedingungen aus den Ergebnissen nicht ohne Weiteres ableiten.

Darüber hinaus beschränkt sich die Untersuchungseinheit auf Wissensarbeitende bei SAP, die aktiv Large Language Models einsetzen. Dabei stammen drei der vier befragten Personen aus der PCG-Einheit, während lediglich Person D die Perspektive technischer Entwicklungsarbeit repräsentiert. Die vier Interviewpartner decken zwar verschiedene Rollen und Tätigkeitsschwerpunkte ab, stellen jedoch keine repräsentative Stichprobe der gesamten SAP-Belegschaft dar. Insbesondere Rollen, die weniger oder gar keinen Kontakt zu KI-Tools haben, sind in der Auswertung nicht vertreten, weshalb die Ergebnisse eher die Perspektive bereits KI-affiner Wissensarbeitender widerspiegeln.

Eine weitere Einschränkung betrifft die Datenerhebung selbst. Da alle Interviews von einem einzelnen Autor durchgeführt wurden, der als internes Mitglied der SAP-Organisation bekannt ist, lässt sich ein Interviewereffekt nicht vollständig ausschließen. Befragte könnten dazu neigen, KI-Nutzung positiver darzustellen als tatsächlich erlebt, um sozial erwünschte Antworten zu geben oder die eigene Kompetenz herauszustellen. Dieser Effekt kann durch die durchgeführte Anonymisierung zwar abgemildert, aber nicht eliminiert werden.

Ergänzend dazu handelt es sich bei der Literaturanalyse um die Arbeit eines einzelnen Autors. Wie in Kapitel 3 im Rahmen der Snyder-Methodik bereits eingeräumt, empfiehlt das methodische Vorgehen idealerweise den Einsatz von zwei Reviewern, um die Reliabilität der Quellenauswahl zu sichern. Da dies im Rahmen einer Einzelarbeit nicht realisierbar war, besteht trotz der dokumentierten Ein- und Ausschlusskriterien ein gewisses Risiko selektiver Quellenauswahl.

Hinzu kommt die kritische Einordnung der herangezogenen grauen Literatur. Wie in Kapitel 3 ausgeführt, stammen mehrere der verwendeten Quellen von Unternehmensberatungen wie BCG, McKinsey, Deloitte und PwC, die selbst kommerzielle KI-Transformationsleistungen anbieten. Ein potenzieller Interessenkonflikt bei der Darstellung von KI-Potenzialen kann trotz der in der Arbeit vorgenommenen kritischen Würdigung und der Kombination mit wissenschaftlichen Quellen nicht vollständig ausgeschlossen werden.

Schließlich ist die Aktualität der verwendeten Literatur als Limitation zu berücksichtigen. Das Forschungsfeld der generativen KI entwickelt sich außergewöhnlich schnell, sodass Studien, die zum Zeitpunkt der Recherche aktuell waren, bereits bei der Fertigstellung der Arbeit durch neuere Erkenntnisse oder veränderte Rahmenbedingungen überholt sein können. Die in dieser Arbeit beschriebenen Veränderungen in Arbeitsprozessen und Kompetenzprofilen sind daher als Momentaufnahme eines sich dynamisch entwickelnden Feldes zu verstehen und nicht als stabile Befundlage.

== Handlungsempfehlungen

Auf Basis der Literaturanalyse sowie der Ergebnisse der Experteninterviews lassen sich im Folgenden konkrete Handlungsempfehlungen für SAP als Organisation sowie für Wissensarbeitende ableiten. Die Empfehlungen orientieren sich an den drei Themenbereichen der Arbeit und adressieren sowohl strukturelle als auch individuelle Handlungsbedarfe.

*Verankerung des Human in the Loop als organisationales Prinzip*

Eine zentrale Erkenntnis aus Literatur und Interviews ist, dass KI-Systeme nicht deterministisch arbeiten und zu Halluzinationen neigen, weshalb die menschliche Prüfinstanz in keinem KI-gestützten Prozess wegfallen darf. SAP sollte das Prinzip des Human in the Loop daher nicht als individuelle Verhaltensempfehlung belassen, sondern als verbindlichen Bestandteil von Prozessdesign und Qualitätssicherung verankern. Konkret bedeutet dies, dass bei der Einführung neuer KI-gestützter Workflows von Beginn an festgelegt werden sollte, welche Ausgaben von wem geprüft werden und welche Eskalationswege bei fehlerhaften Ergebnissen bestehen. Gerade im Bereich der Softwareentwicklung, den Person D exemplarisch beschreibt, sollte KI-generierter Code grundsätzlich einem menschlichen Review unterzogen werden, bevor er produktiv eingesetzt wird.

*Aufbau strukturierter KI-Kompetenz statt individuellem Ausprobieren*

Die Interviews zeigen, dass KI-Nutzung bei SAP bislang stark von der persönlichen Initiative und Affinität der einzelnen Mitarbeitenden abhängt. Während einige Befragte bereits strukturierte Strategien wie Kontext-Prompts oder explizite Nachrechenaufträge entwickelt haben, tasteten sich andere anfangs ohne Orientierung an die Tools heran. SAP sollte daher gezielte Schulungsangebote entwickeln, die über die bloße Tool-Einführung hinausgehen und konkret die Fähigkeit zur kritischen Evaluation von KI-Ausgaben vermitteln. Dabei sollte Prompting als eigenständige Kompetenz behandelt werden, da die Qualität der KI-Ausgabe maßgeblich von der Qualität der Eingabe abhängt. Ergänzend empfiehlt sich der Aufbau eines teamübergreifenden Best-Practice-Katalogs, in dem bewährte Anwendungsfälle, geeignete Tools und Erfahrungen mit typischen Fehlern geteilt werden, um das vorhandene implizite Wissen einzelner Personen für die gesamte Organisation nutzbar zu machen.

*Datenschutz sichtbar machen statt dokumentieren*

Aus den Interviews geht hervor, dass Datenschutzvorgaben zwar existieren, aber häufig nur in internen Wiki-Artikeln hinterlegt sind und von Mitarbeitenden nicht aktiv wahrgenommen werden. Person C kritisiert, dass klare Hinweise fehlen, welche Daten in welches Tool eingegeben werden dürfen, und dass insbesondere das Need-to-Know-Prinzip sowie die Unterscheidung zwischen intern betriebenen und extern gehosteten Modellen vielen Kolleginnen und Kollegen nicht bewusst ist. SAP sollte daher Datenschutzhinweise direkt in den Tool-Oberflächen verankern, etwa durch Hinweistexte am Eingabefeld oder durch automatisierte Warnmeldungen bei erkennbar vertraulichen Inhalten. Darüber hinaus sollte eine zentrale und aktuell gehaltene Übersichtsseite bereitgestellt werden, die klar kommuniziert, welches Tool für welche Zwecke und Vertraulichkeitsstufen freigegeben ist.

*Verlernrisiko aktiv adressieren*

Die Interviews belegen, dass das Risiko des Verlernens besonders in technischen Tätigkeitsfeldern real ist. Person D beschreibt, dass der gedankliche Prozess des eigenständigen Entwickelns zunehmend durch die KI übernommen wird. Gleichzeitig zeigt Person B, dass aktive Auseinandersetzung mit KI-Ergebnissen diesen Effekt teilweise abmildern kann. SAP sollte daher Weiterbildungsmaßnahmen so gestalten, dass sie nicht nur neue KI-Kompetenzen aufbauen, sondern auch bestehende fachliche Fähigkeiten bewusst erhalten. Dies kann etwa durch regelmäßige Aufgaben geschehen, die bewusst ohne KI-Unterstützung bearbeitet werden, oder durch Mentoring-Formate, in denen erfahrene Mitarbeitende ihr implizites Erfahrungswissen an jüngere Kolleginnen und Kollegen weitergeben, bevor es durch KI-Nutzung an Sichtbarkeit verliert. Da das Verlernrisiko, wie in Abschnitt 5.2 dargelegt, besonders in strukturierten Entwicklungsrollen auftritt, sollten entsprechende Maßnahmen gezielt für Mitarbeitende in technischen Entwicklungsrollen konzipiert werden, wie sie in dieser Untersuchung durch Person D repräsentiert werden, anstatt sie pauschal für alle Mitarbeitenden auszurollen.

*KI-Budgets fair und zweckgebunden gestalten*

Sowohl Person B als auch Person D weisen auf ein bisher wenig diskutiertes strukturelles Risiko hin, nämlich dass ungleiche Token-Limits und KI-Budgets zwischen verschiedenen Rollen und Einheiten dazu beitragen könnten, dass bestehende Leistungsunterschiede weiter zunehmen. Wer mehr KI-Kapazität zur Verfügung hat, kann produktiver arbeiten und neue Kompetenzen schneller aufbauen. Da bei SAP mehrere Tools wie EKX, MS Copilot und Claude parallel im Einsatz sind und unterschiedliche Nutzungslimits gelten, ist diese Frage besonders relevant. SAP sollte daher bei der Vergabe von KI-Nutzungsbudgets nicht allein technische oder kostenbezogene Kriterien anlegen, sondern auch den konkreten Arbeitsbedarf der jeweiligen Rolle berücksichtigen. Gleichzeitig sollten Mitarbeitende darin geschult werden, Prompts effizient zu formulieren und den tatsächlichen Nutzwert jedes KI-Einsatzes zu hinterfragen, um Ressourcen gezielt einzusetzen.

*Wissensarbeitende für veränderte Rollenanforderungen vorbereiten*

Schließlich zeigen sowohl die Literatur als auch die Interviews übereinstimmend, dass sich die Rolle von Wissensarbeitenden grundlegend verändert. Routinetätigkeiten werden zunehmend durch KI übernommen, während gleichzeitig die Anforderungen an kontextuelles Urteilsvermögen, kritisches Denken und die Fähigkeit zur Qualitätssicherung steigen. SAP sollte diese Verschiebung aktiv kommunizieren und in die interne Karriere- und Rollenentwicklung einbeziehen. Mitarbeitende sollten verstehen, dass KI keine Bedrohung für ihre Tätigkeit darstellt, sondern eine Erweiterung, die jedoch neue Kompetenzen erfordert. Gleichzeitig sollten Führungskräfte sensibilisiert werden, die wachsende Spreizung zwischen KI-affinen und KI-ablehnenden Mitarbeitenden frühzeitig zu erkennen und durch gezielte Unterstützungsangebote zu adressieren, bevor daraus dauerhafte Kompetenzlücken oder Teamkonflikte entstehen.
