= Auswirkungen von KI-Textgenerierung auf die Wissensarbeit (Ergebnisse der Literaturanalyse)

Das folgende Kapitel stellt die Ergebnisse der durchgeführten Literaturanalyse dar und untersucht, wie KI-Textgenerierung die Wissensarbeit verändert. Dabei gliedert sich die Analyse in die drei Themenbereiche, die im Rahmen der Literaturanalyse in Kapitel 3 identifiziert wurden. Abschnitt 4.1 beleuchtet zunächst, inwiefern sich bestehende Arbeitsprozesse durch den Einsatz von KI verschieben. Darauf aufbauend analysiert Abschnitt 4.2, welche veränderten Anforderungen sich daraus für die Kompetenzprofile von Wissensarbeitenden ergeben. Abschließend zeigt Abschnitt 4.3, welche Chancen und Risiken sich aus diesen Veränderungen ergeben. Die drei Abschnitte bauen dabei aufeinander auf und ermöglichen so einen umfassenden Blick auf die Auswirkungen von KI-Textgenerierung auf die Wissensarbeit.

== Veränderungen von Arbeitsprozessen

Die Literaturanalyse zeigt, dass KI-Textgenerierung die Arbeitsprozesse von Wissensarbeitenden auf mehreren Ebenen verändert. Im Folgenden werden vier zentrale Verschiebungen beschrieben, nämlich die Verlagerung von ausführenden hin zu assistierenden Tätigkeiten, die wachsende Bedeutung der Steuerung und Überwachung von KI-Prozessen, die funktionale Arbeitsteilung zwischen Mensch und Maschine sowie die veränderte Bewertungsgrundlage von Arbeit.

*Verschiebung von Ausführung zu Assistenz*

Die Literaturanalyse legt nahe, dass KI-Textgenerierung die Arbeitsprozesse von Wissensarbeitenden weniger durch eine vollständige Ablösung von Arbeitsplätzen verändert, sondern vielmehr bestehende Tätigkeiten und Aufgaben innerhalb von Rollen verschiebt. Dieses Bild zeigt sich sowohl in wissenschaftlichen Studien als auch in Praxis- und Beratungsberichten (vgl. @carbonero2023[S. 707-708]; vgl. @Agrawal2024[327]; vgl. @Brynjolfsson2025[891, 901, 934-935]; vgl. @bcg2026[S. 1-2, 9-13]; vgl. @deloitte_hct2026[S. 3-5, 8, 11-12, 32]; vgl. @pwc_ai_jobs_barometer_2026[S. 3-19]). Insbesondere routineorientierte Tätigkeiten wie Informationsrecherche, Texterstellung und Dokumentation werden den Quellen zufolge zunehmend durch KI unterstützt, woraus sich interpretieren lässt, dass sich der Arbeitsschwerpunkt stärker auf die Überprüfung, Bewertung und Integration von Ergebnissen verlagert (vgl. @Noy2023ProductivityAI[Abstract, S. 1, 3, 7]; vgl. @Brynjolfsson2025[S. 890, 891]; vgl. @Lee2025[S. 1-2]; vgl. @DellAcqua2026[S. 403, 406, 419-420]). Bereits vor dem Aufkommen generativer KI zeigte sich, dass Wissensarbeitende einen erheblichen Teil ihrer Arbeitszeit für Routineaufgaben aufwenden, wodurch weniger Kapazität für Innovationen und Problemlösungen verbleibt (vgl. @haufe_routine2017). Darüber hinaus deutet die Literatur darauf hin, dass KI überwiegend nicht als Ersatz, sondern als Assistenzsystem verstanden wird, das menschliche Arbeit ergänzt und erweitert. Daraus lässt sich schließen, dass zunehmend hybride Arbeitsformen entstehen, in denen menschliche und technologische Fähigkeiten gemeinsam eingesetzt werden (vgl. @Brynjolfsson2025[891, 901, 934-935]; vgl. @DellAcqua2026[S. 403-404]; vgl. @lei_kim2024[S. 252, 259]; vgl. @bcg2026[S. 1-2, 9-13]; vgl. @deloitte_hct2026[S. 3-5, 8, 11-12, 32]; vgl. @pwc_ai_jobs_barometer_2026[S. 3-19]).

*Steuerung und Überwachung von KI-Prozessen*

Diese Verlagerung hin zur Assistenzfunktion von KI geht mit einer grundlegenden Veränderung der Rolle von Wissensarbeitenden einher. Fast die Hälfte der Befragten gab an, dass sich ihre Rolle zunehmend dahin verschoben habe, KI zu steuern und anzuleiten, anstatt die eigentliche Arbeit selbst auszuführen (vgl. @beauchene2026aiwork[S.3]). Laut McKinsey werden in diesem Zuge neue Rollen erforderlich sein, unter anderem für LLM Selection and Management sowie für das Training und Management von GenAI-Agenten (vgl. @hussin2024genai[S.5]).

Diese Entwicklung zeigt sich auch in spezifischen Berufsfeldern. So verschiebt generative KI nach BCG die Tätigkeit von Softwareentwicklern weg von repetitiven Codieraufgaben hin zu System-Level Thinking, Orchestrierung sowie Produkt- und Designaufgaben, wobei menschliches Urteilsvermögen und Verantwortung weiterhin erforderlich bleiben (vgl. @bcg2026[S.8]). Auf organisationaler Ebene verweist Deloitte auf die Work-Orchestration-Plattform Gloat Mosaic als Beispiel für eine Lösung, die Fähigkeiten, Arbeitsaufgaben und Technologien integriert und Manager sowie Mitarbeitende dabei unterstützt, dynamisch zu entscheiden, ob Aufgaben von Menschen oder Maschinen übernommen werden sollten (vgl. @cantrell2025planningoutcomes).

Neben der Steuerung gewinnt dabei auch die Überwachung von KI-Prozessen an Bedeutung. McKinsey argumentiert, dass die Automatisierung einfacher Tätigkeiten Beschäftigten ermöglicht, sich komplexeren Aufgaben zuzuwenden, die menschliches Urteilsvermögen, Aufsicht und den Umgang mit Mehrdeutigkeit erfordern. Zugleich verweist McKinsey auf eine Studie mit 1.488 US-Beschäftigten, nach der eine intensive Überwachung von KI-Systemen zu kognitiver Ermüdung beitragen kann (vgl. @metakis2026leadai). BCG erwartet in diesem Zusammenhang, dass durch KI neugestaltete Rollen höhere Anforderungen an Fachwissen, Aufsicht und Verantwortlichkeit stellen werden, wobei insbesondere Aufgaben bestehen bleiben, die kontextbezogenes Urteilsvermögen, Koordination und Oversight-Fähigkeiten erfordern (vgl. @bcg2026[S. 11-12, 15]). McKinsey betont ergänzend, dass mit der Einführung generativer KI neue Rollen und Verantwortlichkeiten entstehen, darunter LLMOps-Fähigkeiten zur langfristigen Überwachung der Modellleistung sowie eine stärkere Führungsaufsicht darüber, wie sich Rollen und Arbeitsweisen anpassen müssen (vgl. @hussin2024genai[S. 5]). PwC hebt schließlich hervor, dass Organisationen nicht nur KI-Kompetenzen innerhalb der Belegschaft aufbauen, sondern auch ihre Integrations-, Governance- und Vendor-Management-Fähigkeiten stärken müssen, um KI-Lösungen gezielt steuern zu können (vgl. @pwc_ai_jobs_barometer_2026[S. 17, 19]).

*Routine für KI, Ausnahmen für Menschen*

Mit der Verlagerung hin zu steuernden Tätigkeiten verändert sich auch das konkrete Verhältnis zwischen menschlicher und maschineller Aufgabenbearbeitung. Dabei zeigt sich, dass LLMs häufig strikt an vorgegebene Richtlinien gebunden bleiben, selbst wenn deren Anwendung im konkreten Kontext unpraktisch oder kontraproduktiv ist. Diese Inflexibilität wird auf eine mechanistische Interpretation von Regeln zurückgeführt, während menschliche Entscheidungen häufiger kontextabhängige Anpassungen berücksichtigen. Der Umgang mit Ausnahmen stellt daher eine Form adaptiver Entscheidungsfindung dar, die nuanciertes Urteilsvermögen erfordert (vgl. @disorbo2025exceptions[S. 1,3,14]).

Daraus ergibt sich eine funktionale Arbeitsteilung zwischen Mensch und Maschine. Rollen mit offenen Problemlösungen und häufigen Ausnahmen werden laut der Analyse eher durch KI ergänzt als ersetzt, da sie weiterhin menschliches Urteilsvermögen erfordern. Am Beispiel von Call-Centern zeigt sich eine mögliche Aufgabenteilung, bei der KI standardisierte Erstinteraktionen übernimmt, während Menschen Eskalationen und Ausnahmefälle bearbeiten. Gleichzeitig könnten Einstiegsrollen neu gestaltet werden und früher als bisher Aufgaben wie die Überwachung von KI-Systemen, das Management von Ausnahmen und komplexere Problemlösungen umfassen (vgl. @bcg2026[S. 3-7, 15]). In der Praxis bedeutet dies, dass durch den Einsatz von KI Mitarbeitende zwar von einfachen, wiederkehrenden Anfragen entlastet werden, ihre Tätigkeit sich jedoch stärker hin zu komplexen und eskalierten Fällen verschiebt. Während KI das Grundrauschen einfacher Aufgaben übernimmt, verbleiben bei Menschen die anspruchsvolleren Fälle, wodurch die kognitive Intensität der Arbeit steigen kann (vgl. @brassey2026brainpowered).

*Qualität statt Geschwindigkeit*

Die veränderte Aufgabenteilung zwischen Mensch und KI hat nicht nur Auswirkungen auf die Art der Tätigkeiten, sondern auch auf den Maßstab, nach dem Arbeit bewertet wird. Während in klassischen Arbeitsprozessen Effizienz oft als zentrales Kriterium galt, rückt mit dem Einsatz von KI zunehmend die Ergebnisqualität in den Vordergrund. Hintergrund hierfür ist, dass Machine-Learning-Code im Gegensatz zu klassischem Softwarecode nicht auf deterministischen Wenn-Dann-Regeln basiert, sondern auf statistischen Verfahren. Aufgrund seines nicht-deterministischen Charakters kann dieselbe Eingabe zu unterschiedlichen Ausgaben führen, was ML-Systeme grundlegend von deterministischen Programmen unterscheidet (vgl. @hu2022lora[S.2-3,7-8]). Ergänzend dazu werden KI-Halluzinationen als ein inhärentes technisches Merkmal der probabilistischen Generierungsmechanismen großer Sprachmodelle eingeordnet (vgl. @cheng2026trust[S.1]).

Dieser nicht-deterministische Charakter schlägt sich in einem Spannungsverhältnis zwischen Effizienz und Verantwortlichkeit nieder. Nutzer bevorzugen in praktischen Anwendungssituationen häufig direkte und schnell umsetzbare Antworten gegenüber einem tieferen Verständnis der zugrunde liegenden Entscheidungsprozesse. Eine starke Effizienzorientierung kann jedoch das Risiko einer übermäßigen Abhängigkeit von KI-Systemen erhöhen, wodurch die kritische Bewertung von KI-generierten Ergebnissen beeinträchtigt werden kann (vgl. @spatola2024efficiency[S.1-2,5]). Ebenso zeigt sich, dass eine Steigerung der Bearbeitungsgeschwindigkeit nicht zwangsläufig zu einer Verbesserung der Qualität der Ergebnisse führt (vgl. @spivack2024cognition[S.5]).

Folgerichtig verändert der Einsatz von KI die Rolle von Wissensarbeitenden in Richtung einer stärkeren Qualitätssicherung. Im Bereich der Softwareentwicklung beispielsweise müssen Entwickler zunehmend als Reviewer agieren und KI-generierten Code hinsichtlich Fehlern, Kompatibilität und Wartbarkeit bewerten, was erweiterte Fähigkeiten zur Analyse und Qualitätssicherung erfordert (vgl. @hussin2024genai[S.3-4]). Dabei steigen auch die allgemeinen Erwartungen an Arbeitsergebnisse. Befragte geben an, dass die Anforderungen an das, was als ausreichend gilt, gestiegen sind, und 52 % berichten, dass sie mehr Zeit für die Überprüfung und Korrektur von KI-generierten Ergebnissen aufwenden (vgl. @beauchene2026aiwork[S.17]). In sicherheitskritischen Bereichen können KI-Halluzinationen darüber hinaus erhebliche Auswirkungen haben, etwa wenn fehlerhafte diagnostische Vorschläge im Gesundheitswesen klinische Risiken erhöhen oder in anderen Bereichen durch notwendige Überprüfungen zusätzliche Aufwände entstehen (vgl. @cheng2026trust[S. 4]). Schließlich zeigt sich, dass für die Ausrichtung von LLMs an menschlichem Urteilsvermögen nicht nur entscheidend ist, welche Entscheidungen getroffen werden, sondern auch, wie diese zustande kommen, wobei insbesondere das Training mit menschlichen Erklärungen eine wichtige Rolle spielt (vgl. @disorbo2025exceptions[S.1-2]).

#parbreak()
Zusammenfassend lässt sich aus den gesichteten Quellen ableiten, dass KI-Textgenerierung die Wissensarbeit nicht durch Stellenabbau verändert, sondern durch eine mehrstufige Verschiebung von Tätigkeitsschwerpunkten. Routineaufgaben werden zunehmend durch KI übernommen, während Wissensarbeitende stärker in steuernde, überwachende und bewertende Rollen wechseln. Dabei entsteht eine funktionale Arbeitsteilung, in der KI standardisierbare Prozesse abwickelt und der Mensch Ausnahmen, Qualitätssicherung und kontextabhängige Entscheidungen verantwortet. Da KI-Systeme nicht deterministisch arbeiten und zu Halluzinationen neigen, verschiebt sich der Bewertungsmaßstab von Effizienz hin zur Ergebnisqualität. Die Verantwortung für die Richtigkeit und Verwendbarkeit von Arbeitsergebnissen verbleibt damit beim Menschen.

== Veränderungen der Kompetenzprofile

Die in Abschnitt 4.1 beschriebenen Verschiebungen in den Arbeitsprozessen ziehen veränderte Anforderungen an die Kompetenzprofile von Wissensarbeitenden nach sich. Die Literaturanalyse identifiziert dabei vier zentrale Themenbereiche, nämlich die steigende Bedeutung von KI-Kompetenz und kritischem Denken, den wachsenden Wert impliziten Erfahrungswissens, die Relevanz von Fachkompetenz und kontextuellem Urteilsvermögen sowie die Notwendigkeit kontinuierlichen Lernens und der Requalifizierung.

*KI-Kompetenz und kritisches Denken*

Die Analyse der Literatur zeigt, dass sich durch KI-Textgenerierung nicht nur Arbeitsprozesse verändern, sondern auch die Anforderungen an die Kompetenzprofile von Wissensarbeitenden. Über nahezu alle Quellen hinweg lässt sich erkennen, dass technologische Kompetenzen zunehmend durch menschliche Fähigkeiten ergänzt werden müssen und künftig nicht mehr allein fachliches Wissen über den beruflichen Erfolg entscheidet (vgl. @Lee2025[S.1]; vgl. @Gerlich2025[1-2, 14]). Besonders häufig zeigt sich dabei die steigende Bedeutung von KI-Kompetenz. Den Quellen zufolge müssen Wissensarbeitende lernen, KI-Systeme effektiv einzusetzen, ihre Ergebnisse zu interpretieren sowie deren Grenzen und Risiken zu verstehen (vgl. @rafi2024[S. 1-2, 7]; vgl. @bcg2026[S. 15, 18-19]; vgl. @deloitte_hct2026[S. 3-5, 8, 11-12, 32]). Da KI-generierte Inhalte Fehler, Verzerrungen oder Halluzinationen enthalten können, lässt sich daraus schließen, dass kritisches Denken und menschliche Urteilskraft nicht an Bedeutung verlieren, sondern im Gegenteil unverzichtbar bleiben (vgl. @Lee2025[S. 12, 15-16]; @Brynjolfsson2025[S. 897]; vgl. @DellAcqua2026[S. 3]; vgl. @Woodruff2024[S. 7 und 23]).

*Erfahrungswissen als Wettbewerbsvorteil*

Neben explizit vermittelbaren Kompetenzen wie KI-Literacy rückt mit dem Aufkommen von KI auch eine weniger greifbare Wissensform in den Fokus, nämlich das implizite Erfahrungswissen. Explizites Wissen bezeichnet Wissen, das leicht dokumentiert, formalisiert und kommuniziert werden kann, beispielsweise in Form von Anleitungen oder Rezepten. Implizites Wissen basiert dagegen auf persönlicher Erfahrung, Intuition und situativem Verständnis und lässt sich nur schwer verbalisieren oder vollständig kodifizieren, wie etwa die Fähigkeit, beim Fahrradfahren das Gleichgewicht zu halten (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 9]). Dabei handelt es sich häufig um Wissen, dessen Besitz oder Erwerb den Handelnden nicht vollständig bewusst ist (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 1, 7]). Implizites Wissen umfasst dabei drei Formen. Erstens gibt es Wissen, das zwar theoretisch kodifizierbar wäre, dessen Überführung in explizite Information jedoch zu kostspielig ist. Zweitens zählt dazu Wissen über sprachliche Nuancen und Subtexte. Drittens gehört verkörpertes Wissen dazu, das durch sensorische Erfahrungen erworben wird (vgl. @lu2025tacit[S. 1-2]).

Genau an diesem Punkt stoßen LLMs an ihre Grenzen. Sie basieren auf Repräsentationsmodellen, die Muster aus großen Mengen textueller Daten lernen und diese für Sprachgenerierung und Verständnis nutzen. Da ein Teil des impliziten Wissens subjektiv, erfahrungsbasiert und kaum textualisiert ist, stellt dessen Erfassung durch LLMs eine besondere Herausforderung dar (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 2]). Besonders deutlich wird dieser Unterschied im Bereich des verkörperten Wissens, denn während LLMs sprachliche Muster und Zusammenhänge aus Trainingsdaten lernen können, verfügen sie nicht über physische Erfahrungen oder sensorische Interaktionen mit der Welt und können daher beispielsweise Kälte beschreiben, ohne jemals körperlich zu frieren (vgl. @lu2025tacit[S. 2, 10, 17]). Kritiker argumentieren darüber hinaus, dass LLMs lediglich statistische Zusammenhänge in Textdaten erfassen und keine menschliche Form von semantischem Verständnis besitzen (vgl. @lu2025tacit[S. 6-7]).

Daraus ergibt sich, dass implizites Erfahrungswissen durch die Verbreitung von KI nicht an Wert verliert, sondern im Gegenteil an Bedeutung gewinnt. KI kann bestehendes Wissen erweitern und Aufgaben beschleunigen, ersetzt jedoch nicht vollständig menschliches Urteilsvermögen, Mustererkennung und implizites Wissen, die durch wiederholte praktische Erfahrung in realen Situationen entstehen (vgl. @brassey2026brainpowered). Menschen können zudem bei bestimmten Aufgaben weiterhin einen komparativen Vorteil besitzen, insbesondere wenn für das Training von KI-Modellen nicht ausreichend aufgezeichnete Daten verfügbar sind oder deren Erhebung wirtschaftlich nicht sinnvoll wäre (vgl. @lu2025tacit[S. 16]).

*Fachkompetenz und kontextuelles Urteilsvermögen*

Eng verbunden mit dem Wert impliziten Wissens ist die Frage, welche Fachkompetenzen künftig besonders gefragt sind. Während stark strukturierte und wiederholbare Tätigkeiten eher für eine Automatisierung geeignet sind, bleiben Rollen mit offenen Problemlösungen und häufigen Ausnahmen stärker auf menschliches Urteilsvermögen angewiesen und werden daher eher durch KI augmentiert als ersetzt. Mitarbeitende können dabei als Eskalationsschicht fungieren, wenn KI-Agenten komplexe Fälle oder Ausnahmesituationen nicht bewältigen können (vgl. @bcg2026[S.4, 16]). McKinsey zeigt in diesem Zusammenhang, dass stark KI-exponierte Rollen Aufgaben mit menschlich geprägten Fähigkeiten wie Empathie, Urteilsvermögen und Kreativität 2,5-mal schneller aufnehmen als weniger KI-exponierte Rollen (vgl. @brassey2026brainpowered).

Besondere Bedeutung kommt dabei dem kontextuellen Urteilsvermögen zu. KI kann zwar strukturierte Aufgaben übernehmen und Prozesse beschleunigen, ersetzt jedoch nicht vollständig das menschliche Urteilsvermögen, das für die Interpretation emotionaler und sozialer Hinweise sowie für kontextabhängige Entscheidungen notwendig ist. Besonders Rollen mit hohen Anforderungen an Interaktion, Vertrauen und kontextuelles Urteil werden daher eher durch KI ergänzt als ersetzt (vgl. @bcg2026[S. 7-8, 11-12]). Da bestimmte Fähigkeiten wie Problemlösung, Urteilsvermögen und der Umgang mit organisationsspezifischem Wissen schwer formal zu vermitteln sind, gewinnen zudem Lehrlingsmodelle und Mentoring an Bedeutung, bei denen erfahrene Experten durch praktische Zusammenarbeit und Vorbildfunktion institutionelles Wissen sowie schwer vermittelbare Kompetenzen an jüngere Mitarbeitende weitergeben (vgl. @hussin2024genai[S. 8]).

*Kontinuierliches Lernen und Requalifizierung*

Angesichts der beschriebenen Verschiebungen in Arbeitsprozessen und Kompetenzprofilen stellt sich schließlich die Frage, wie Wissensarbeitende und Organisationen auf diese Veränderungen reagieren können. Der zunehmende Einsatz von KI wird erhebliche Veränderungen der Arbeitswelt bewirken. Schätzungen zufolge werden in den nächsten zwei bis drei Jahren etwa 50 % bis 55 % der Arbeitsplätze in den USA durch KI verändert. Für viele Beschäftigte bedeutet dies keine vollständige Ersetzung ihrer bisherigen Tätigkeit, sondern eine Veränderung der Arbeitsanforderungen und Aufgabenprofile. Unternehmen stehen daher vor der Herausforderung, strategische Maßnahmen zur Weiterbildung und Umschulung ihrer Mitarbeitenden zu entwickeln (vgl. @bcg2026[S.1,13]).

Der Bedarf an Weiterbildung wird von vielen Beschäftigten als zunehmend relevant wahrgenommen. So geben 88 % der Befragten an, dass sie in den nächsten fünf Jahren eine umfassende Weiterqualifizierung benötigen, während sich lediglich 36 % als ausreichend geschult einschätzen (vgl. @beauchene2026aiwork[S.11-13]). Aufgrund der kontinuierlichen Weiterentwicklung von KI-Technologien wird Weiterbildung dabei nicht als einmalige Maßnahme ausreichen, sondern Beschäftigte werden voraussichtlich häufiger Weiterqualifizierungen benötigen, um ihre Fähigkeiten an veränderte Anforderungen anzupassen (vgl. @bcg2026[S.18]). Die Einführung von KI-Systemen erfordert darüber hinaus nicht nur die Weiterentwicklung technischer Kompetenzen, sondern auch den Erhalt der kognitiven Leistungsfähigkeit der Beschäftigten. Das Konzept des Brain Capital betrachtet Gehirngesundheit und geistige Fähigkeiten als strategische Ressource. Ohne entsprechende Maßnahmen besteht das Risiko kognitiver Überlastung, insbesondere wenn Weiterbildungs- und Transformationsprozesse zusätzliche Anforderungen schaffen, ohne ausreichende Kapazitäten und Erholungsphasen zu berücksichtigen (vgl. @brassey2026brainpowered).

*Datenschutz- und Sicherheitskompetenz*

Das TrustLLM-Framework definiert Datenschutz (Privacy) als eines von acht grundlegenden Prinzipien für vertrauenswürdige, menschenzentrierte Large Language Models. Zu den weiteren Prinzipien zählen Sicherheit, Wahrhaftigkeit, Fairness, Robustheit, Transparenz, Rechenschaftspflicht und Machine Ethics (vgl. @atakiyev2025explainability[S.22]).

Auch für Wissensarbeitende ergibt sich daraus die Anforderung, grundlegende Kompetenzen im Umgang mit KI-Risiken aufzubauen. Am Beispiel von Softwarefachkräften wird deutlich, dass dazu insbesondere das Verständnis verschiedener Risikoarten und der Einsatz geeigneter Schutzmaßnahmen gehören (vgl. @hussin2024genai[S.6]). Darüber hinaus sollten Wissensarbeitende, die KI-Lösungen von Drittanbietern einsetzen, über grundlegende Kenntnisse in den Bereichen Governance und Vendor Management verfügen, um externe Modelle wirksam steuern zu können (vgl. @pwc_ai_jobs_barometer_2026[S.17]). Im Zuge der zunehmenden KI-Nutzung entstehen zudem neue spezialisierte Rollen, die sich auf KI-Sicherheit und Datenverantwortung konzentrieren (vgl. @hussin2024genai[S.5]). Erschwerend kommt hinzu, dass in vielen Unternehmen klare Governance-Strukturen für die Zusammenarbeit von Menschen und KI-Systemen noch fehlen, sodass Mitarbeitende und Führungskräfte de facto eine erhöhte Eigenverantwortung tragen (vgl. @beauchene2026aiwork[S.27]).

#parbreak()
Zusammenfassend verdeutlicht die Literaturanalyse, dass sich die Kompetenzanforderungen an Wissensarbeitende in mehrere Richtungen gleichzeitig verschieben. KI-Kompetenz und kritisches Denken werden zur Grundvoraussetzung, da KI-generierte Inhalte stets bewertet und hinterfragt werden müssen. Gleichzeitig gewinnt implizites Erfahrungswissen an Wert, weil LLMs auf explizitem Textwissen basieren und situatives Urteilen, verkörpertes Wissen und kontextabhängige Entscheidungen nicht replizieren können. Tiefe Fachkompetenz bleibt erforderlich, um Ausnahmen zu erkennen und KI-Ausgaben gegen Erfahrungswissen zu prüfen. Hinzu kommt Datenschutz- und Sicherheitskompetenz als neue Querschnittsanforderung, da fehlende Governance-Strukturen die Eigenverantwortung der Wissensarbeitenden beim Umgang mit vertraulichen Daten erhöhen. Da sich diese Anforderungen kontinuierlich weiterentwickeln, wird nicht mehr allein fachliches Wissen, sondern die Fähigkeit zur dauerhaften Requalifizierung zum entscheidenden Merkmal zukunftsfähiger Wissensarbeit.

== Chancen und Risiken

Aus den in Abschnitt 4.1 und 4.2 beschriebenen Veränderungen ergeben sich sowohl Chancen als auch Risiken für Wissensarbeitende.

*Chancen*

Eine zentrale Chance ergibt sich aus der in Abschnitt 4.1 beschriebenen Entlastung von Routinetätigkeiten. Da KI standardisierbare Aufgaben zunehmend übernimmt, gewinnen Wissensarbeitende zeitliche Kapazitäten für komplexere und wertschöpfende Tätigkeiten, sodass mehr Raum für strategisches Denken, Ideenentwicklung und kreative Problemlösung entsteht.

Eine weitere Chance liegt in der Stärkung menschlicher Kernkompetenzen. Wie in Abschnitt 4.2 gezeigt, können LLMs implizites Erfahrungswissen, kontextuelles Urteilsvermögen und situatives Entscheiden nicht replizieren. Der Mensch bleibt in komplexen Ausnahmesituationen daher unverzichtbar, und genau diese Kompetenzen gewinnen durch den KI-Einsatz an Sichtbarkeit und Wert.

Darüber hinaus eröffnet die in Abschnitt 4.1 beschriebene Mensch-KI-Kollaboration neue Möglichkeiten der Aufgabenverteilung. Organisationen können Prozesse flexibler gestalten, indem KI standardisierte Erstinteraktionen übernimmt und Menschen sich auf Eskalationen, Ausnahmen und Entscheidungen mit hohem Kontextbedarf konzentrieren.

*Risiken*

Den Chancen stehen jedoch erhebliche Risiken gegenüber. Ein zentrales Risiko besteht in Fehlentscheidungen durch unkritische KI-Nutzung. Wie in Abschnitt 4.1 dargelegt, arbeiten KI-Systeme nicht deterministisch und neigen zu Halluzinationen. Wer KI-generierte Ergebnisse ungeprüft übernimmt, riskiert inhaltlich falsche Ausgaben als Grundlage für Entscheidungen zu verwenden. Da die Verantwortung für Ergebnisqualität beim Menschen verbleibt, stellt die fehlende kritische Prüfung ein strukturelles Risiko dar, das mit zunehmendem KI-Einsatz an Gewicht gewinnt.

Ein weiteres Risiko betrifft den Kompetenzaufbau bei Berufsanfängern. KI bietet weniger erfahrenen Beschäftigten kurzfristig die Möglichkeit, Aufgaben schneller und mit besseren Ergebnissen zu bearbeiten, sodass Leistungsunterschiede zu erfahrenen Mitarbeitenden zunächst sinken. Gleichzeitig sind es genau diese Einstiegsaufgaben, über die Berufsanfänger traditionell praktische Erfahrung und implizites Wissen aufbauen. Wie in Abschnitt 4.2 beschrieben, lässt sich implizites Erfahrungswissen nur durch wiederholte Praxis in realen Situationen entwickeln. Werden diese Aufgaben durch KI automatisiert, entfällt dieser Lernpfad, sodass der kurzfristige Leistungsgewinn langfristig auf Kosten des Kompetenzaufbaus gehen kann.

Schließlich besteht das Risiko einer wachsenden Qualifikationslücke. Der in Abschnitt 4.2 beschriebene Bedarf an kontinuierlicher Requalifizierung trifft nicht alle Beschäftigten gleichermaßen. Wer KI-Kompetenz, kritisches Denken und die Bereitschaft zur dauerhaften Weiterentwicklung nicht aufbaut, läuft Gefahr, mit den veränderten Anforderungen nicht Schritt halten zu können. Zugleich besteht das Risiko kognitiver Überlastung, wenn Weiterbildungs- und Transformationsprozesse zusätzliche Anforderungen schaffen, ohne ausreichende Kapazitäten zu berücksichtigen.

Ein weiteres Risiko ergibt sich aus der in Abschnitt 4.2 beschriebenen Datenschutz- und Sicherheitskompetenz. Da in vielen Unternehmen Governance-Strukturen für den KI-Einsatz noch fehlen, sind Wissensarbeitende zunehmend selbst dafür verantwortlich, den sicheren Umgang mit vertraulichen Daten sicherzustellen. Wer diese Kompetenz nicht aufbaut, riskiert unbewusst vertrauliche Informationen an externe Modelle weiterzugeben oder Compliance-Vorgaben zu verletzen, ohne sich dessen bewusst zu sein.

#parbreak()
Zusammenfassend zeigt sich, dass die durch KI ausgelösten Veränderungen in Arbeitsprozessen und Kompetenzprofilen weder ausschließlich positiv noch ausschließlich negativ zu bewerten sind. Die Chancen liegen vor allem in der Entlastung von Routinetätigkeiten, der Aufwertung menschlicher Kernkompetenzen und flexibleren Formen der Zusammenarbeit. Dem gegenüber stehen Risiken durch unkritische KI-Nutzung, den Wegfall klassischer Lernpfade für Berufsanfänger und eine wachsende Qualifikationslücke. Entscheidend wird sein, ob Wissensarbeitende und Organisationen die notwendigen Kompetenzen und Strukturen aufbauen, um KI verantwortungsvoll einzusetzen und die menschliche Urteilskraft dauerhaft zu erhalten.


*Security*
Das TrustLLM-Framework definiert Datenschutz (Privacy) als eines von acht grundlegenden Prinzipien für vertrauenswürdige, menschenzentrierte Large Language Models. Zu den weiteren Prinzipien zählen Sicherheit, Wahrhaftigkeit, Fairness, Robustheit, Transparenz, Rechenschaftspflicht und Machine Ethics (vgl. @atakiyev2025explainability[S.22]).

Im Kontext von Datenschutz gelten Datenlecks in generierten Inhalten sowie die Offenlegung vertraulicher Informationen durch Jailbreaking als zentrale Risiken von Large Language Models. LLM-Erklärungen können dazu beitragen, potenzielle Datenlecks oder die Offenlegung vertraulicher Informationen zu erkennen, indem sie die Quellen der generierten Inhalte offenlegen.(vgl. @atakiyev2025explainability[S.23]).

Organisationen sollten ihre Kompetenzen in den Bereichen Governance, Vendor Management und Integration stärken. Insbesondere benötigen Personen, die KI-Lösungen beschaffen, die Fähigkeit, diese wirksam zu steuern (vgl. @pwc_ai_jobs_barometer_2026[S.17]).

Im Zuge der zunehmenden Nutzung generativer KI können neue Rollen entstehen, die sich beispielsweise auf KI-Sicherheit und Datenverantwortung konzentrieren (vgl. @hussin2024genai[S.5]).

In vielen Unternehmen fehlen bislang klare Governance-Strukturen für die Zusammenarbeit von Menschen und KI-Systemen. Besonders Mitarbeitende und Führungskräfte berichten, dass entsprechende Leitlinien für den Umgang mit Mensch-KI-Teams noch nicht vollständig etabliert sind (vgl. @beauchene2026aiwork[S.27]).

Auch für Wissensarbeitende ergibt sich die Anforderung, grundlegende Kompetenzen im Umgang mit KI-Risiken aufzubauen. Am Beispiel von Softwarefachkräften wird deutlich, dass dazu insbesondere das Verständnis verschiedener Risikoarten und der Einsatz geeigneter Schutzmaßnahmen gehören (vgl. @hussin2024genai[S.6]).




//
// ============================================================
// ALTE TODO-TEXTE ZUM VERGLEICH
// ============================================================
//
// --- TODO: Doing → Orchestration ---
// - Rollenverschiebung: weg von Ausführen, hin zu Steuern/Koordinieren von KI-Prozessen
// - Kernkompetenz wird: KI-Prozesse zielgerichtet lenken, nicht mehr selbst produzieren
// Managing AI" und "Directing AI"
// Fast die Hälfte der Befragten gab an, dass sich ihre Rolle zunehmend dahin verschoben habe, KI zu steuern und anzuleiten, anstatt die eigentliche Arbeit selbst auszuführen (vgl. @beauchene2026aiwork[S.3]). Laut McKinsey (2025) werden neue Rollen erforderlich sein, unter anderem für LLM Selection and Management sowie für das Training und Management von GenAI-Agenten (vgl. @hussin2024genai[S.5]).
//
// "Orchestration" (Orchestrierung)
// Nach BCG verschiebt generative KI die Tätigkeit von Softwareentwicklern weg von repetitiven Codieraufgaben hin zu System-Level Thinking, Orchestrierung sowie Produkt- und Designaufgaben, wobei menschliches Urteilsvermögen und Verantwortung weiterhin erforderlich bleiben (vgl. @bcg2026[S.8]).
// Deloitte verweist auf die Work-Orchestration-Plattform Gloat Mosaic als Beispiel für eine Lösung, die Fähigkeiten, Arbeitsaufgaben und Technologien integriert. Die Plattform unterstützt Manager und Mitarbeitende dabei, dynamisch zu entscheiden, ob Aufgaben von Menschen oder Maschinen übernommen werden sollten (vgl. @cantrell2025planningoutcomes).
//
// "Oversight" (Aufsicht/Überwachung)
// McKinsey argumentiert, dass die Automatisierung einfacher Tätigkeiten Beschäftigten ermöglicht, sich komplexeren Aufgaben zuzuwenden, die menschliches Urteilsvermögen, Aufsicht und den Umgang mit Mehrdeutigkeit erfordern. Zugleich verweist McKinsey auf eine Studie mit 1.488 US-Beschäftigten, nach der eine intensive Überwachung von KI-Systemen zu kognitiver Ermüdung („brain fry") beitragen kann (vgl. @metakis2026leadai).
// BCG erwartet, dass durch KI neugestaltete Rollen höhere Anforderungen an Fachwissen, Aufsicht und Verantwortlichkeit stellen werden. Gleichzeitig bleiben insbesondere Aufgaben bestehen, die kontextbezogenes Urteilsvermögen, Koordination und Oversight-Fähigkeiten erfordern, die häufig durch Berufserfahrung entwickelt werden (vgl. @bcg2026[S. 11-12, 15]).
// McKinsey betont, dass mit der Einführung generativer KI neue Rollen und Verantwortlichkeiten entstehen. Dazu gehören unter anderem LLMOps-Fähigkeiten zur langfristigen Überwachung der Modellleistung sowie eine stärkere Führungsaufsicht darüber, wie sich Rollen und Arbeitsweisen anpassen müssen (vgl. @hussin2024genai[S. 5]).
// Steuerung („Steer")
// PwC betont, dass Organisationen nicht nur KI-Kompetenzen innerhalb der Belegschaft aufbauen müssen, sondern auch ihre Integrations-, Governance- und Vendor-Management-Fähigkeiten stärken sollten. Unternehmen, die KI-Lösungen einkaufen, benötigen demnach die Fähigkeit, diese gezielt zu steuern („steer") (vgl. @pwc_ai_jobs_barometer_2026[S. 17, 19]).
//
//
// --- TODO: Tacit vs. Explicit Knowledge ---
// - Explizites Wissen = dokumentierbar (Wikis, Handbücher) → LLMs gut darin
// - Implizites Wissen = Erfahrungswissen, situatives Urteilen, nicht dokumentierbar → LLMs können das nicht
// - Folgerung: Implizites Wissen wird durch KI wertvoller, nicht weniger relevant
//
// Explizites Wissen bezeichnet Wissen, das leicht dokumentiert, formalisiert und kommuniziert werden kann, beispielsweise in Form von Anleitungen oder Rezepten. Implizites Wissen („tacit knowledge") basiert dagegen auf persönlicher Erfahrung, Intuition und situativem Verständnis und lässt sich nur schwer verbalisieren oder vollständig kodifizieren, wie etwa die Fähigkeit, beim Fahrradfahren das Gleichgewicht zu halten (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 9]).
// Implizites Wissen („tacit knowledge") beschreibt das intuitive Verständnis hinter Expertenurteilen und Fähigkeiten, das auf persönlicher Erfahrung beruht und sich nur schwer verbalisieren oder formalisieren lässt. Zudem handelt es sich häufig um Wissen, dessen Besitz oder Erwerb den Handelnden nicht vollständig bewusst ist (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 1, 7]).
// Implizites Wissen kann in drei Formen unterschieden werden: Wissen, das zwar theoretisch kodifizierbar wäre, dessen Überführung in explizite Information jedoch zu kostspielig ist; Wissen über sprachliche Nuancen und Subtexte; sowie verkörpertes Wissen, das durch sensorische Erfahrungen erworben wird (vgl. @lu2025tacit[S. 1-2]).
// 2. LLMs basieren primär auf explizitem Wissen
// LLMs basieren auf Repräsentationsmodellen, die Muster aus großen Mengen textueller Daten lernen und diese für Sprachgenerierung und Verständnis nutzen. Da ein Teil des impliziten Wissens subjektiv, erfahrungsbasiert und kaum textualisiert ist, stellt dessen Erfassung durch LLMs eine besondere Herausforderung dar (vgl. @atakiyev2025explainability[S. 14]; @lu2025tacit[S. 2]).
// Ein zentraler Unterschied zwischen menschlichem und durch LLMs verarbeitetem Wissen liegt im Bereich des verkörperten Wissens („embodied knowledge"). Während LLMs sprachliche Muster und Zusammenhänge aus Trainingsdaten lernen können, verfügen sie nicht über physische Erfahrungen oder sensorische Interaktionen mit der Welt. Daher können sie beispielsweise Kälte beschreiben, ohne jemals körperlich zu frieren (vgl. @lu2025tacit[S. 2, 10, 17]).
// Kritiker argumentieren, dass LLMs lediglich statistische Zusammenhänge in Textdaten erfassen und keine menschliche Form von semantischem Verständnis besitzen (vgl. @lu2025tacit[S. 6-7]).
// 3. Warum Erfahrungswissen durch KI an Bedeutung gewinnt
// KI kann bestehendes Wissen erweitern und Aufgaben beschleunigen, ersetzt jedoch nicht vollständig menschliches Urteilsvermögen, Mustererkennung und implizites Wissen, die durch wiederholte praktische Erfahrung in realen Situationen entstehen (vgl. @brassey2026brainpowered).
// McKinsey argumentiert, dass Automatisierung Beschäftigte von einfacheren Tätigkeiten entlasten kann, sodass mehr Zeit für komplexere Aufgaben entsteht, die menschliches Urteilsvermögen, Aufsicht und den Umgang mit Unsicherheit erfordern. Gleichzeitig zeigen die Ergebnisse, dass stark KI-exponierte Rollen Aufgaben mit menschlich geprägten Fähigkeiten wie Empathie, Urteilsvermögen und Kreativität 2,5-mal schneller aufnehmen als weniger KI-exponierte Rollen (vgl. @brassey2026brainpowered).
// Während stark strukturierte und wiederholbare Tätigkeiten eher für eine Automatisierung geeignet sind, bleiben Rollen mit offenen Problemlösungen und häufigen Ausnahmen stärker auf menschliches Urteilsvermögen angewiesen. Diese Rollen werden daher eher durch KI augmentiert als ersetzt. Zudem können menschliche Mitarbeitende als Eskalationsschicht fungieren, wenn KI-Agenten komplexe Fälle oder Ausnahmefälle nicht bewältigen können (vgl. @bcg2026[S.4, 16]).
// Da bestimmte Fähigkeiten wie Problemlösung, Urteilsvermögen und der Umgang mit organisationsspezifischem Wissen schwer formal zu vermitteln sind, gewinnen Lehrlingsmodelle und Mentoring an Bedeutung. Erfahrene Experten können durch praktische Zusammenarbeit und Vorbildfunktion institutionelles Wissen sowie schwer vermittelbare Kompetenzen an jüngere Mitarbeitende weitergeben (vgl. @hussin2024genai[S. 8]).
// Menschen können bei bestimmten Aufgaben weiterhin einen komparativen Vorteil besitzen, insbesondere wenn für das Training von KI-Modellen nicht ausreichend aufgezeichnete Daten verfügbar sind oder deren Erhebung wirtschaftlich nicht sinnvoll wäre. In solchen Bereichen kann menschliches Erfahrungswissen weiterhin eine wichtige Rolle spielen (vgl. @lu2025tacit[S. 16]).
//
//
// --- TODO: Domain Expertise + Exception Management ---
// - LLMs übernehmen Routine → menschlicher Beitrag verlagert sich auf Ausnahmen
// - Tiefe Fachkompetenz nötig, um KI-Ausgaben gegen Erfahrungswissen zu prüfen
// - Exception Handling, ethische Abwägungen, Nicht-Standard-Situationen bleiben beim Menschen
//
// 1. "Exception Handling" (Umgang mit Ausnahmen)
// Die Studie untersucht die Fähigkeit von LLMs, mit Ausnahmen in Entscheidungsprozessen umzugehen. Die Ergebnisse zeigen, dass LLMs häufig strikt an vorgegebene Richtlinien gebunden bleiben, selbst wenn deren Anwendung im konkreten Kontext unpraktisch oder kontraproduktiv ist. Diese Inflexibilität wird auf eine „mechanistische Interpretation" von Regeln zurückgeführt, während menschliche Entscheidungen häufiger kontextabhängige Anpassungen berücksichtigen. Der Umgang mit Ausnahmen stellt daher eine Form adaptiver Entscheidungsfindung dar, die nuanciertes Urteilsvermögen erfordert (vgl. @disorbo2025exceptions[S. 1,3,14]).
// Rollen mit offenen Problemlösungen und häufigen Ausnahmen werden laut der Analyse eher durch KI ergänzt als ersetzt, da sie weiterhin menschliches Urteilsvermögen erfordern. Am Beispiel von Call-Centern zeigt sich eine mögliche Arbeitsteilung: KI übernimmt standardisierte Erstinteraktionen, während Menschen Eskalationen und Ausnahmefälle bearbeiten. Gleichzeitig könnten Einstiegsrollen neu gestaltet werden und früher als bisher Aufgaben wie die Überwachung von KI-Systemen, das Management von Ausnahmen und komplexere Problemlösungen umfassen (vgl. @bcg2026[S. 3-7, 15]).
// Durch den Einsatz von KI können Mitarbeitende im Kundenservice von einfachen, wiederkehrenden Anfragen entlastet werden. Gleichzeitig verschiebt sich ihre Tätigkeit jedoch stärker hin zu komplexen und eskalierten Fällen. Während KI das „Grundrauschen" einfacher Aufgaben übernimmt, verbleiben bei Menschen die anspruchsvolleren Fälle, wodurch die kognitive Intensität der Arbeit steigen kann (vgl. @brassey2026brainpowered).
// 2. Kontextuelles Urteilsvermögen (Contextual Judgment)
// KI kann zwar strukturierte Aufgaben übernehmen und Prozesse beschleunigen, ersetzt jedoch nicht vollständig das menschliche Urteilsvermögen, das für die Interpretation emotionaler und sozialer Hinweise sowie für kontextabhängige Entscheidungen notwendig ist. Besonders Rollen mit hohen Anforderungen an Interaktion, Vertrauen und kontextuelles Urteil werden daher eher durch KI ergänzt als ersetzt (vgl. @bcg2026[S. 7-8, 11-12]).
//
//
// --- TODO: Efficiency Focus → Outcome Focus ---
// - Früher: Wie mache ich es effizienter?
// - Künftig: Stimmt das Endergebnis? Ist es inhaltlich korrekt und verwendbar?
// - Begründung: KI nicht deterministisch, Halluzinationen möglich → Qualitätskontrolle des Outputs wird zentral
//
// Machine-Learning-Code basiert im Gegensatz zu klassischem Softwarecode nicht auf deterministischen Wenn-Dann-Regeln, sondern auf statistischen Verfahren. Aufgrund seines nicht-deterministischen Charakters kann dieselbe Eingabe zu unterschiedlichen Ausgaben führen. Diese inhärente Unvorhersehbarkeit unterscheidet ML-Systeme grundlegend von deterministischen Programmen. In diesem Zusammenhang bezeichnen die Autoren Machine-Learning-Code als „lawless", da seine Nicht-Deterministik eine eindeutige Vorhersagbarkeit und damit eine Analogie zum Verständnis von „Code as Law" einschränkt (vgl. @hu2022lora[S.2-3,7-8]).
// Ergänzend dazu werden KI-Halluzinationen als ein inhärentes technisches Merkmal der probabilistischen Generierungsmechanismen großer Sprachmodelle eingeordnet (vgl. @cheng2026trust[S.1]).
// Darüber hinaus zeigt sich bei der Integration von KI-Systemen ein Spannungsverhältnis zwischen Effizienz und Verantwortlichkeit. Nutzer bevorzugen in praktischen Anwendungssituationen häufig direkte und schnell umsetzbare Antworten gegenüber einem tieferen Verständnis der zugrunde liegenden Entscheidungsprozesse. Eine starke Effizienzorientierung kann jedoch das Risiko einer übermäßigen Abhängigkeit von KI-Systemen erhöhen, wodurch die kritische Bewertung von KI-generierten Ergebnissen beeinträchtigt werden kann (vgl. @spatola2024efficiency[S.1-2,5]).
// Der Einsatz von KI-Systemen kann bestimmte Aspekte der Wissensarbeit, insbesondere die Arbeitsgeschwindigkeit, verbessern. Eine Steigerung der Bearbeitungsgeschwindigkeit führt jedoch nicht zwangsläufig zu einer Verbesserung der Qualität der Ergebnisse (vgl. @spivack2024cognition[S.5]).
// Im Bereich der Softwareentwicklung verändert der Einsatz generativer KI-Systeme die Rolle von Entwicklern. Anstatt ausschließlich Code zu erstellen, müssen Entwickler zunehmend als Reviewer agieren und KI-generierten Code hinsichtlich Fehlern, Kompatibilität und Wartbarkeit bewerten. Diese veränderte Rolle erfordert erweiterte Fähigkeiten zur Analyse und Qualitätssicherung, insbesondere um potenzielle Probleme im generierten Code zu identifizieren und zu beheben (vgl. @hussin2024genai[S.3-4]).
// Der Einsatz von KI-Systemen verändert zudem die Erwartungen an die Qualität von Arbeitsergebnissen. Befragte geben an, dass die Anforderungen an das, was als „gut genug" gilt, gestiegen sind. Gleichzeitig berichten 52 % der Befragten, dass sie mehr Zeit für die Überprüfung und Korrektur von KI-generierten Ergebnissen aufwenden (vgl. @beauchene2026aiwork[S.17]).
// Für die Ausrichtung großer Sprachmodelle an menschlichen Entscheidungsmaßstäben ist nicht nur entscheidend, welche Entscheidungen getroffen werden, sondern auch, wie diese Entscheidungen zustande kommen. Die Ergebnisse zeigen, dass das Training mit menschlichen Erklärungen eine bessere Anpassung an menschliches Urteilsvermögen ermöglichen kann (vgl. @disorbo2025exceptions[S.1-2]).
// In sicherheitskritischen Anwendungsbereichen können KI-Halluzinationen erhebliche Auswirkungen haben. Im Gesundheitswesen können beispielsweise fehlerhafte diagnostische Vorschläge klinische Risiken erhöhen, während in anderen Bereichen zusätzliche Aufwände durch die notwendige Überprüfung KI-generierter Informationen entstehen (vgl. @cheng2026trust[S. 4]).
// Für die Ausrichtung von LLMs an menschlichem Urteilsvermögen ist nicht nur entscheidend, welche Entscheidungen getroffen werden, sondern auch, wie diese Entscheidungen zustande kommen. Die Studie zeigt, dass insbesondere das Training mit menschlichen Erklärungen eine wichtige Rolle für die Anpassung von KI-Systemen an menschliche Entscheidungsprozesse spielt (vgl. @disorbo2025exceptions[S.1-2]).
//
//
// --- TODO: Transformationspfad / Ausbildung ---
// - Continuous Learning / Reskilling als dauerhafte Anforderung
// - Ausbildungsformate weg von Routine-Einübung → hin zu Exception Handling, kritischem Urteilen, KI-Umgang
// - Skill-based statt job-based: flexible Kompetenzportfolios statt fixer Stellenbeschreibungen
//
// Der zunehmende Einsatz von KI wird erhebliche Veränderungen der Arbeitswelt bewirken. Schätzungen zufolge werden in den nächsten zwei bis drei Jahren etwa 50 % bis 55 % der Arbeitsplätze in den USA durch KI verändert werden. Für viele Beschäftigte bedeutet dies keine vollständige Ersetzung ihrer bisherigen Tätigkeit, sondern eine Veränderung der Arbeitsanforderungen und Aufgabenprofile. Unternehmen stehen daher vor der Herausforderung, strategische Maßnahmen zur Weiterbildung und Umschulung ihrer Mitarbeitenden zu entwickeln (vgl. @bcg2026[S.1,13]).
// Der Bedarf an Weiterbildung wird von vielen Beschäftigten als zunehmend relevant wahrgenommen. 88 % der Befragten geben an, dass sie in den nächsten fünf Jahren eine umfassende Weiterqualifizierung („major upskilling") benötigen, während sich lediglich 36 % als ausreichend geschult einschätzen (vgl. @beauchene2026aiwork[S.11-13]).
// Aufgrund der kontinuierlichen Weiterentwicklung von KI-Technologien wird Weiterbildung nicht als einmalige Maßnahme ausreichen. Stattdessen werden Beschäftigte voraussichtlich häufiger Weiterqualifizierungen benötigen, um ihre Fähigkeiten an veränderte Anforderungen anzupassen (vgl. @bcg2026[S.18]).
// Die Einführung von KI-Systemen erfordert nicht nur die Weiterentwicklung technischer Kompetenzen, sondern auch den Erhalt der kognitiven Leistungsfähigkeit der Beschäftigten. Das Konzept des „Brain Capital" betrachtet Gehirngesundheit und geistige Fähigkeiten als strategische Ressource. Ohne entsprechende Maßnahmen besteht das Risiko kognitiver Überlastung („brain fry"), insbesondere wenn Weiterbildungs- und Transformationsprozesse zusätzliche Anforderungen schaffen, ohne ausreichende Kapazitäten und Erholungsphasen zu berücksichtigen (vgl. @brassey2026brainpowered).
//
//
// --- TODO: Fehlentscheidungen durch unkritische KI-Nutzung ---
// - Risiko: Nutzende vertrauen blind dem KI-Output, obwohl LLM halluziniert oder Fehler liefert
// - Outcome stimmt nicht, weil kein menschliches Urteil dazwischentritt
// - Verbindung zum Outcome-Fokus aus 4.2: wer nicht prüft, bekommt falsches Ergebnis
