= Experteninterviews, Diskussion und Handlungsempfehlungen

Das folgende Kapitel ergänzt die Literaturanalyse aus Kapitel 4 um eine empirische Perspektive und verfolgt dabei drei aufeinander aufbauende Ziele. Abschnitt 5.1 stellt zunächst die Durchführung der Experteninterviews dar und wertet die Aussagen der vier befragten Wissensarbeitenden bei SAP thematisch aus. Darauf aufbauend gleicht Abschnitt 5.2 die Interviewergebnisse mit den theoretischen Befunden aus Kapitel 4 ab, um zu prüfen, inwiefern die Literatur durch die Praxisperspektiven gestützt, ergänzt oder herausgefordert wird. Abschnitt 5.3 benennt anschließend die methodischen Limitationen der Untersuchung, bevor Abschnitt 5.4 auf Basis der gewonnenen Erkenntnisse konkrete Handlungsempfehlungen für SAP ableitet.

== Durchführung und Auswertung der Interviews

Zur Beantwortung der Forschungsfrage wurden ergänzend zur Literaturanalyse leitfadengestützte Experteninterviews durchgeführt. Als Grundlage für die Gespräche diente ein Interviewleitfaden, der im Rahmen der Vorbereitung entwickelt wurde und im Anhang in @interview-leitfaden eingesehen werden kann. Parallel dazu wurden geeignete Interviewpartner aus dem Unternehmensumfeld von SAP identifiziert, kontaktiert und die Gesprächstermine koordiniert.

*Durchführung der Experteninterviews*

Im Vorfeld jedes Interviews wurden die Teilnehmenden über die Zielsetzung und den Kontext der Arbeit informiert, um einen gemeinsamen Ausgangspunkt zu schaffen. Die Interviews fanden jeweils unabhängig voneinander in Form von Videokonferenzen statt und dauerten durchschnittlich ca. 30 Minuten. Um einen natürlichen Gesprächsfluss zu ermöglichen, wurde die Reihenfolge der Fragen flexibel gehandhabt. Mit ausdrücklicher Zustimmung der Teilnehmenden wurden die Gespräche aufgezeichnet, sodass eine sorgfältige Auswertung im Nachgang möglich war. Darüber hinaus wurden die Teilnehmenden zu Beginn des Gesprächs darauf hingewiesen, dass ihre Aussagen sowie ihre Person vollständig anonymisiert behandelt werden.

*Auswertung der Experteninterviews*

Im Folgenden werden die Aussagen der vier Interviewpartner thematisch verglichen, um Gemeinsamkeiten und Unterschiede systematisch herauszuarbeiten. Die vollständigen Gesprächsprotokolle sind im Anhang in @interview-auswertung-wolff bis @interview-auswertung-d einzusehen.

Personen A, B und C sind alle in derselben internen Beratungseinheit von SAP tätig, wobei Person A im Projektmanagement (ca. 4–5 Jahre), Person B mit Fokus auf interne KI-Projekte (ca. 15 Jahre) und Person C in einem Transformationsprojekt im Bereich Kundenkommunikation (ca. 20 Jahre bei SAP) arbeiten. Person D ist seit 2019 als Senior Developer in einer Softwareentwicklungsabteilung bei SAP tätig. Damit repräsentieren Personen A, B und C eher beratungs- und projektnahe Wissensarbeit, während Person D die Perspektive technischer Entwicklungsarbeit einbringt.

Hinsichtlich der KI-Tool-Nutzung setzen alle vier Interviewpartner die Tools regelmäßig, teils täglich ein. Die eingesetzten Werkzeuge variieren dabei je nach Tätigkeitsschwerpunkt. So nutzen Personen A und C primär EKX sowie MS Copilot für Texte und Dokumentenanalyse, Person B setzt KI-Tools für PM-Aufgaben und als Sparring-Partner ein, während Person D den Fokus auf Codegenerierung und technische Dokumentation legt. Als Hemmfaktoren bei Kolleginnen und Kollegen benennen alle Befragten übereinstimmend initiale Skepsis gegenüber neuen Technologien, fehlendes Vertrauen in die Zuverlässigkeit der Tools sowie mangelnde Kenntnis über sinnvolle Anwendungsfälle.

Im Hinblick auf die Veränderungen im Arbeitsalltag beschreiben alle Befragten einen spürbaren Wandel, wenngleich in unterschiedlicher Ausprägung. Person A berichtet, administrative Aufgaben zunehmend zu delegieren und dadurch mehr Kapazität für strategisch-inhaltliche Themen zu gewinnen. Person C schätzt die persönliche Geschwindigkeitssteigerung im aktuellen Projekt auf ca. 10 %, verweist jedoch auf deutlich höhere Potenziale in Projekten mit Massendaten. Demgegenüber weist Person B darauf hin, dass der Prüfaufwand für KI-generierte Ergebnisse die Zeitersparnis teilweise kompensiere. Person D beschreibt eine strukturelle Veränderung, da das Team angehalten sei, bei jeder Problemstellung aktiv zu prüfen, ob KI-Einsatz sinnvoll sei, und Dokumentation heute standardmäßig KI-unterstützt erstellt werde.

Bei der Frage nach der Eignung von Aufgaben für KI stimmen die Befragten darin überein, dass Formulierungsaufgaben, Texterstellung und Zusammenfassungen besonders geeignet sind. Person C ergänzt dabei einen spezifischen Gesichtspunkt und stellt den Datenschutz als primären Eignungsfilter heraus, da vor jeder inhaltlichen Abwägung geprüft werden müsse, ob personenbezogene oder vertrauliche Daten betroffen seien. Person D benennt Code-Analyse ebenfalls als geeigneten Anwendungsfall, zieht jedoch eine klare Grenze, sobald viele voneinander abhängige Klassen und Objekte im Spiel sind und die Modelle den Kontextüberblick verlieren.

Im Umgang mit fehlerhaften KI-Ausgaben zeigen alle Befragten ein ähnliches Muster, nämlich kritisches Hinterfragen und eigenständige Verifikation. Person A schildert dabei einen Fall, in dem MS Copilot durch einen Transkriptionsfehler wiederholt ein nicht existierendes Projekt erfand und die gesamte 90-minütige Aufzeichnung abgehört werden musste, um die Fehlerquelle zu finden. Vergleichbar beschreibt Person D den Fall eines Kollegen, dem die KI zu einer ABAP-Syntax-Frage eine klare, aber faktisch falsche Antwort gab, die der offiziellen Dokumentation widersprach. Als Reaktion darauf hat Person B einen Kontext-Prompt entwickelt, der die KI zu Rückfragen und Selbstkorrektur anhält, während Person C empfiehlt, bei numerischen Auswertungen explizit nachrechnen zu lassen.

Im Bereich Datenschutz zeigen alle Befragten ein ausgeprägtes Bewusstsein, das sich in konkreten Verhaltensregeln niederschlägt. So werden übereinstimmend keine personenbezogenen Daten an KI-Tools weitergegeben. Ergänzend dazu kritisiert Person C, dass klare Vorgaben oft nur in internen Wiki-Artikeln hinterlegt sind und nicht direkt am Eingabefeld der Tools erscheinen. Person D hebt zudem hervor, dass eine menschliche Prüfinstanz im Sinne eines Human in the Loop bei jedem KI-unterstützten Entwicklungsschritt obligatorisch sei.

Beim Verlernrisiko und den veränderten Kompetenzanforderungen zeigen sich deutliche Unterschiede zwischen den Befragten. Person D gibt offen zu, nicht mehr zu wissen, wann zuletzt eigenständig ABAP-Code entwickelt wurde, da der gedankliche Entwicklungsprozess zunehmend durch die KI übernommen werde. Person B sieht das grundsätzliche Risiko zwar ebenfalls, erkennt in der aktiven Auseinandersetzung mit KI-Ergebnissen jedoch einen möglichen Ausgleich. Personen A und C berichten hingegen nicht von einem Verlerneffekt. Als neue Schlüsselkompetenz nennen Personen A und B übereinstimmend gezieltes Prompting sowie die kritische Evaluation von KI-Outputs.

Hinsichtlich der Vorteile des KI-Einsatzes stimmen alle Befragten darin überein, dass Zeitersparnis und Qualitätssteigerung bei analytischen und dokumentarischen Aufgaben die zentralen Stärken der Tools sind. Darüber hinaus weisen sowohl Person B als auch Person D auf eine wachsende Spreizung zwischen KI-affinen und KI-ablehnenden Mitarbeitenden hin sowie auf ungleiche Token-Limits als potenzielle neue Form organisationaler Chancenungleichheit.

== Diskussion der Ergebnisse im Abgleich mit der Literatur

Die Ergebnisse der Experteninterviews werden im Folgenden den Befunden der Literaturanalyse aus Kapitel 4 gegenübergestellt. Ziel ist es, zu prüfen, inwiefern die in der Literatur beschriebenen Veränderungen in Arbeitsprozessen, Kompetenzprofilen sowie Chancen und Risiken durch die Praxiserfahrungen der befragten Wissensarbeitenden bei SAP nicht falsifiziert, ergänzt oder widerlegt werden.

*Veränderungen von Arbeitsprozessen*

Die Literaturanalyse zeigt, dass KI-Textgenerierung Arbeitsprozesse vor allem durch eine Verlagerung von ausführenden hin zu steuernden und überwachenden Tätigkeiten verändert, ohne dabei Arbeitsplätze vollständig zu ersetzen. Dieses Bild spiegelt sich in den Interviews deutlich wider. Sämtliche befragte Personen beschreiben, dass KI-Tools routineorientierte Aufgaben wie Texterstellung, Dokumentation oder Codeanalyse übernehmen, während sie selbst zunehmend in prüfende, bewertende oder steuernde Rollen wechseln. Person A berichtet, dass administrative Aufgaben zunehmend an KI delegiert werden und dadurch mehr Kapazität für strategisch-inhaltliche Tätigkeiten entsteht, was der in der Literatur beschriebenen Entlastung von Routineaufgaben nicht widerspricht. In ähnlicher Weise beschreibt Person D, dass das Team angehalten sei, bei jeder Problemstellung aktiv zu prüfen, ob KI-Einsatz sinnvoll sei, was die von McKinsey und BCG beschriebene Steuerungsrolle des Menschen in KI-gestützten Prozessen in der Praxis veranschaulicht.

Auch die in der Literatur beschriebene Verschiebung des Qualitätsmaßstabs von Effizienz hin zur Ergebnisqualität findet in den Interviews eine klare Entsprechung. Alle Befragten betonen, dass KI-Ausgaben stets kritisch geprüft werden müssen und nicht unbesehen übernommen werden können. Person D schildert dabei exemplarisch, dass unkritisch übernommener KI-Code langfristig kaum wartbar wäre. Person B ergänzt, dass der Prüfaufwand für KI-generierte Ergebnisse die Zeitersparnis teilweise kompensiere, was das von der BCG-Studie beschriebene Spannungsverhältnis zwischen Effizienz und Verantwortlichkeit in der Praxis widerspiegelt.

*Veränderungen der Kompetenzprofile*

Die Literatur identifiziert KI-Kompetenz und kritisches Denken als zentrale neue Anforderungen an Wissensarbeitende. Dieser Befund wird durch sämtliche Interviews gestützt. Personen A und B benennen gezieltes Prompting sowie die kritische Evaluation von KI-Outputs als die wichtigsten neu entstandenen Fähigkeiten in ihrer Arbeitspraxis. Darüber hinaus sprechen die Interviews für die von der Literatur beschriebene Notwendigkeit kontinuierlichen Lernens. Person B berichtet, dass die Fähigkeit zur strukturierten Evaluation von KI-Ergebnissen im Team noch aktiv entwickelt werden müsse, während Person D die Umstellung von Word-Dateien auf Markdown als konkrete neue technische Anforderung beschreibt, die zunächst eine Lernhürde darstellte.

Besonders deutlich zeigt sich in den Interviews die Relevanz von Datenschutz- und Sicherheitskompetenz, die die Literatur als wachsende Querschnittsanforderung beschreibt. Person C hebt hervor, dass Datenschutz als primärer Filter vor jeder inhaltlichen Eignung von KI-Aufgaben stehe, und kritisiert, dass klare Vorgaben in vielen Tools nicht direkt am Eingabefeld erscheinen, sondern nur in internen Wiki-Artikeln hinterlegt sind. Damit spricht diese Aussage nicht nur für den in der Literatur beschriebenen Kompetenzaufbau als Notwendigkeit, sondern weist auch auf eine möglicherweise strukturelle Lücke hin, die zumindest bei SAP beobachtbar ist und in der Literatur so nicht explizit thematisiert wird.

Das in der Literatur beschriebene Risiko des Cognitive Offloading, also der Schwächung kognitiver Fähigkeiten durch zunehmende Delegation an KI, findet in den Interviews eine differenzierte Entsprechung. Person D beschreibt offen, dass der gedankliche Entwicklungsprozess beim eigenständigen Coden zunehmend durch die KI übernommen werde und das Verlernrisiko real sei. Person B sieht das grundsätzliche Risiko ebenfalls, erkennt in der aktiven Auseinandersetzung mit KI-Ergebnissen jedoch einen möglichen Ausgleich. Personen A und C hingegen berichten nicht von einem Verlerneffekt, was darauf hindeutet, dass das Risiko stark von der Art der Tätigkeit und dem Grad der KI-Nutzung abhängt. Ein weiterer Einflussfaktor ist dabei das eigene Kompetenzniveau im jeweiligen Themengebiet, da Wissensarbeitende, die KI-Outputs nicht eigenständig beurteilen können, kognitive Kontrolle abgeben, ohne dies bewusst wahrzunehmen.

Dieser Befund führt zu einer eigenständigen Hypothese (H1), die so in der gesichteten Literatur nicht explizit formuliert wird. Das Verlernrisiko durch KI-Nutzung ist demnach nicht generell vorhanden oder abwesend, sondern ausgeprägt tätigkeitsabhängig. Es tritt besonders dann auf, wenn Wissensarbeitende KI für strukturierte, wiederholbare kognitive Kernprozesse ihrer Rolle einsetzen, wie etwa das eigenständige Entwickeln von Code. In projektnaher oder beratender Wissensarbeit hingegen, wo Tätigkeiten ohnehin stärker durch Kontexturteil, Kommunikation und situative Entscheidungen geprägt sind, scheint das Risiko deutlich geringer ausgeprägt zu sein.

*Chancen und Risiken*

Die in der Literatur beschriebene zentrale Chance der Entlastung von Routineaufgaben wird durch alle vier Interviews nicht widerlegt. Besonders prägnant zeigt sich dies bei Person C, die bei der Analyse umfangreicher Compliance-Dokumente über deutliche Zeitersparnisse berichtet, sowie bei Person D, für die KI bei der Zusammenfassung langer Dokumente erhebliche Kapazitäten freisetzt. Ergänzend dazu beschreibt Person B, dass sich die gleichzeitige Betreuung mehrerer Projekte durch KI-Unterstützung deutlich vereinfacht habe, was die in der Literatur beschriebene Entlastung von Routinetätigkeiten durch KI in der Praxis nicht widerlegt.

Die in der Literatur als zentrales Risiko beschriebenen Fehlentscheidungen durch unkritische KI-Nutzung werden durch alle Interviewpartner aus eigener Erfahrung veranschaulicht. So schildert Person A, wie MS Copilot durch eine Fehlerquelle im Transkript ein nicht existierendes Projekt erfand und den gesamten Prüfaufwand erhöhte, während Person D beschreibt, wie das KI-Tool zu einer ABAP-Syntax-Frage eine klare, aber faktisch falsche Antwort gab. Beide Fälle veranschaulichen, dass die in der Literatur beschriebene kontinuierliche menschliche Validierung nicht nur theoretisch notwendig, sondern in der Praxis unerlässlich ist.

Das Risiko einer wachsenden Qualifikationslücke, das die Literatur vor allem im Hinblick auf unterschiedliche Adoptionsgeschwindigkeiten beschreibt, tritt in den Interviews in Form eines konkreten Teamphänomens zutage. Sowohl Person B als auch Person D berichten von einer zunehmenden Spreizung zwischen KI-affinen und KI-ablehnenden Kolleginnen und Kollegen, die zu Ungleichgewichten in Teams führen könne. Darüber hinaus ergänzen die Interviews einen Aspekt, der in der Literatur weniger prominent behandelt wird, nämlich die Frage der Token-Kosten und KI-Budgets. Person D sowie Person B weisen darauf hin, dass ungleiche Nutzungslimits zwischen Rollen eine neue Form der Chancenungleichheit schaffen können, die Organisationen aktiv adressieren müssen.

Insgesamt zeigt der Abgleich, dass sich die in der Literatur beschriebenen Veränderungen in Arbeitsprozessen, Kompetenzanforderungen sowie Chancen und Risiken durch die Interviewergebnisse in weiten Teilen nicht falsifizieren lassen. Gleichzeitig ergänzen die Praxisperspektiven die theoretischen Befunde an mehreren Stellen, insbesondere hinsichtlich der strukturellen Datenschutzlücken in Tool-Oberflächen, der situativen Ausprägung des Verlernrisikos sowie der bisher wenig diskutierten Frage der KI-Budgetverteilung als organisationale Gerechtigkeitsfrage.

Aus dem Abgleich lassen sich dabei drei Hypothesen ableiten, die so in der gesichteten Literatur nicht explizit formuliert werden und als Ausgangspunkt für weiterführende Untersuchungen dienen können.

*H1:* Das Verlernrisiko durch KI-Nutzung ist nicht pauschal vorhanden oder abwesend, sondern abhängig davon, ob KI strukturierte kognitive Kernprozesse in bestimmten Situationen ersetzt oder lediglich ergänzt.

*H2:* Eine strukturelle Datenschutzlücke besteht nicht nur auf der Kompetenzebene der Mitarbeitenden, sondern auf der Gestaltungsebene der Tool-Oberflächen selbst, da Datenschutzhinweise dort häufig nicht sichtbar verankert sind.

*H3:* Die ungleiche Verteilung von KI-Nutzungsbudgets zwischen Rollen eröffnet eine neue Dimension organisationaler Chancenungleichheit, die in der bisherigen Forschung zu KI und Wissensarbeit kaum thematisiert wird.

Diese drei Hypothesen stellen den empirischen Eigenbeitrag der vorliegenden Arbeit dar und sollten in Folgestudien mit größeren Stichproben überprüft werden.

== Limitationen der Untersuchung

Die vorliegende Arbeit weist eine Reihe von Einschränkungen auf, die bei der Interpretation der Ergebnisse berücksichtigt werden müssen.

Eine erste Limitation ergibt sich aus dem gewählten Forschungsdesign als Einzelfallstudie nach Yin. Wie in Kapitel 3 dargelegt, wurde SAP als Revelatory Case ausgewählt, da der Forscher als internes Mitglied der Organisation einen Feldzugang besitzt, der externen Forschern weitgehend verschlossen ist. Gleichzeitig schränkt diese Entscheidung die Übertragbarkeit der Ergebnisse auf andere Unternehmen und Branchen erheblich ein. Da SAP im Vergleich zu vielen anderen Unternehmen eine fortgeschrittene LLM-Adoption aufweist, lassen sich Aussagen über die Veränderung von Wissensarbeit durch KI in Unternehmen mit geringerer Adoptionsreife, anderen Organisationsstrukturen oder anderen regulatorischen Rahmenbedingungen aus den Ergebnissen nicht ohne Weiteres ableiten.

Darüber hinaus beschränkt sich die Untersuchungseinheit auf Wissensarbeitende bei SAP, die aktiv Large Language Models einsetzen. Dabei stammen drei der vier befragten Personen aus der internen Beratungseinheit von SAP, während lediglich Person D die Perspektive technischer Entwicklungsarbeit repräsentiert. Die vier Interviewpartner decken zwar verschiedene Rollen und Tätigkeitsschwerpunkte ab, stellen jedoch keine repräsentative Stichprobe der gesamten SAP-Belegschaft dar. Insbesondere Rollen, die weniger oder gar keinen Kontakt zu KI-Tools haben, sind in der Auswertung nicht vertreten, weshalb die Ergebnisse eher die Perspektive bereits KI-affiner Wissensarbeitender widerspiegeln.

Eine weitere Einschränkung betrifft die Datenerhebung selbst. Da alle Interviews von einem einzelnen Autor durchgeführt wurden, der als internes Mitglied der SAP-Organisation bekannt ist, lässt sich ein Interviewereffekt nicht vollständig ausschließen. Befragte könnten dazu neigen, KI-Nutzung positiver darzustellen als tatsächlich erlebt, um sozial erwünschte Antworten zu geben oder die eigene Kompetenz herauszustellen. Dieser Effekt kann durch die durchgeführte Anonymisierung zwar abgemildert, aber nicht eliminiert werden.

Ergänzend dazu handelt es sich bei der Literaturanalyse um die Arbeit eines einzelnen Autors. Wie in Kapitel 3 im Rahmen der Snyder-Methodik bereits eingeräumt, empfiehlt das methodische Vorgehen idealerweise den Einsatz von zwei Reviewern, um die Reliabilität der Quellenauswahl zu sichern. Da dies im Rahmen einer Einzelarbeit nicht realisierbar war, besteht trotz der dokumentierten Ein- und Ausschlusskriterien ein gewisses Risiko selektiver Quellenauswahl.

Hinzu kommt die kritische Einordnung der herangezogenen grauen Literatur. Wie in Kapitel 3 ausgeführt, stammen mehrere der verwendeten Quellen von Unternehmensberatungen wie BCG, McKinsey, Deloitte und PwC, die selbst kommerzielle KI-Transformationsleistungen anbieten. Ein potenzieller Interessenkonflikt bei der Darstellung von KI-Potenzialen kann trotz der in der Arbeit vorgenommenen kritischen Würdigung und der Kombination mit wissenschaftlichen Quellen nicht vollständig ausgeschlossen werden.

Schließlich ist die Aktualität der verwendeten Literatur als Limitation zu berücksichtigen. Das Forschungsfeld der generativen KI entwickelt sich außergewöhnlich schnell, sodass Studien, die zum Zeitpunkt der Recherche aktuell waren, bereits bei der Fertigstellung der Arbeit durch neuere Erkenntnisse oder veränderte Rahmenbedingungen überholt sein können. Die in dieser Arbeit beschriebenen Veränderungen in Arbeitsprozessen und Kompetenzprofilen sind daher als Momentaufnahme eines sich dynamisch entwickelnden Feldes zu verstehen und nicht als stabile Befundlage.

== Handlungsempfehlungen

Auf Basis der Literaturanalyse sowie der Ergebnisse der Experteninterviews lassen sich im Folgenden konkrete Handlungsempfehlungen für SAP als Organisation sowie für Wissensarbeitende ableiten. Die Empfehlungen orientieren sich an den drei Themenbereichen der Arbeit und adressieren sowohl strukturelle als auch individuelle Handlungsbedarfe.

*Verankerung des Human in the Loop als organisationales Prinzip*

Wie in Kapitel 4.1 dargestellt, arbeiten KI-Systeme nicht deterministisch und neigen zu Halluzinationen, weshalb die menschliche Prüfinstanz in keinem KI-gestützten Prozess wegfallen darf. SAP sollte das Prinzip des Human in the Loop daher nicht als individuelle Verhaltensempfehlung belassen, sondern als verbindlichen Bestandteil von Prozessdesign und Qualitätssicherung verankern. Konkret bedeutet dies, dass bei der Einführung neuer KI-gestützter Workflows von Beginn an festgelegt werden sollte, welche Ausgaben von wem geprüft werden und welche Korrektur- und Eskalationswege bei fehlerhaften Ergebnissen bestehen. Gerade im Bereich der Softwareentwicklung, den Person D exemplarisch beschreibt, sollte KI-generierter Code grundsätzlich einem menschlichen Review unterzogen werden, bevor er produktiv eingesetzt wird.

*Aufbau strukturierter KI-Kompetenz statt individuellem Ausprobieren*

Die Interviews zeigen, dass KI-Nutzung bei SAP bislang stark von der persönlichen Initiative und Affinität der einzelnen Mitarbeitenden abhängt. Während einige Befragte bereits strukturierte Strategien wie Kontext-Prompts oder explizite Nachrechenaufträge entwickelt haben, tasteten sich andere anfangs ohne Orientierung an die Tools heran. SAP sollte daher bestehende Schulungsangebote ausbauen und weiterentwickeln, sodass sie über die bloße Tool-Einführung hinausgehen und konkret die Fähigkeit zur kritischen Evaluation von KI-Ausgaben vermitteln. Dabei sollte Prompting als eigenständige Kompetenz behandelt werden, da die Qualität der KI-Ausgabe maßgeblich von der Qualität der Eingabe abhängt. Ergänzend empfiehlt sich der Aufbau eines teamübergreifenden Best-Practice-Katalogs, in dem bewährte Anwendungsfälle, geeignete Tools und Erfahrungen mit typischen Fehlern geteilt werden, um das vorhandene implizite Wissen einzelner Personen für die gesamte Organisation nutzbar zu machen.

*Datenschutz sichtbar machen statt dokumentieren*

Aus den Interviews geht hervor, dass Datenschutzvorgaben zwar existieren, aber häufig nur in internen Wiki-Artikeln hinterlegt sind und von Mitarbeitenden nicht aktiv wahrgenommen werden. Person C kritisiert, dass klare Hinweise fehlen, welche Daten in welches Tool eingegeben werden dürfen, und dass insbesondere das Need-to-Know-Prinzip sowie die Unterscheidung zwischen intern betriebenen und extern gehosteten Modellen vielen Kolleginnen und Kollegen nicht bewusst ist. SAP sollte daher Datenschutzhinweise direkt in den Tool-Oberflächen verankern, etwa durch Hinweistexte am Eingabefeld oder durch automatisierte Warnmeldungen bei erkennbar vertraulichen Inhalten. Darüber hinaus sollte die bestehende Übersichtsseite für freigegebene Tools konsequent aktuell gehalten und um alle im Einsatz befindlichen Werkzeuge ergänzt werden, sodass Mitarbeitende jederzeit nachvollziehen können, welches Tool für welche Zwecke und Vertraulichkeitsstufen freigegeben ist.

*Verlernrisiko aktiv adressieren*

Die Interviews belegen, dass das Risiko des Verlernens besonders in technischen Tätigkeitsfeldern real ist. Person D beschreibt, dass der gedankliche Prozess des eigenständigen Entwickelns zunehmend durch die KI übernommen wird. Gleichzeitig zeigt Person B, dass aktive Auseinandersetzung mit KI-Ergebnissen diesen Effekt teilweise abmildern kann. SAP sollte daher Weiterbildungsmaßnahmen so gestalten, dass diese nicht nur neue KI-Kompetenzen aufbauen, sondern auch bestehende fachliche Fähigkeiten bewusst erhalten. SAP sollte dabei zunächst systematisch erfassen, in welchen Situationen KI strukturierte kognitive Kernprozesse ersetzt statt ergänzt, um darauf aufbauend gezielte Maßnahmen für diese Tätigkeitsfelder zu entwickeln, anstatt sie pauschal für alle Mitarbeitenden auszurollen. Ergänzend empfehlen sich Mentoring-Formate, in denen erfahrene Mitarbeitende ihr implizites Erfahrungswissen an jüngere Kolleginnen und Kollegen weitergeben, bevor entsprechende Aufgaben vollständig durch KI übernommen werden.

*KI-Budgets fair und zweckgebunden gestalten*

Sowohl Person B als auch Person D weisen auf ein bisher wenig diskutiertes strukturelles Risiko hin, nämlich dass ungleiche Token-Limits und KI-Budgets zwischen verschiedenen Rollen und Einheiten dazu beitragen könnten, dass bestehende Leistungsunterschiede weiter zunehmen. Den Interviewaussagen zufolge könnte ein ungleicher Zugang zu KI-Kapazitäten dazu führen, dass betroffene Mitarbeitende produktiver arbeiten und Kompetenzen schneller aufbauen, was bestehende Leistungsunterschiede weiter verstärken würde. Da bei SAP mehrere Tools wie EKX, MS Copilot und Claude parallel im Einsatz sind und unterschiedliche Nutzungslimits gelten, ist diese Frage besonders relevant. SAP sollte bei der Vergabe von KI-Nutzungsbudgets weiterhin nicht allein technische oder kostenbezogene Kriterien anlegen, sondern den konkreten Arbeitsbedarf der jeweiligen Rolle konsequent berücksichtigen und diesen Ansatz rollenbezogen weiter ausbauen. Gleichzeitig sollte das bestehende Schulungsangebot zur effizienten Prompt-Formulierung und zum kritischen Hinterfragen des tatsächlichen KI-Nutzwerts weiter ausgebaut werden, um Ressourcen noch gezielter einzusetzen.

*Wissensarbeitende für veränderte Rollenanforderungen vorbereiten*

Schließlich zeigen sowohl die Literatur als auch die Interviews übereinstimmend, dass sich die Rolle von Wissensarbeitenden grundlegend verändert. Routinetätigkeiten werden zunehmend durch KI übernommen, während gleichzeitig die Anforderungen an kontextuelles Urteilsvermögen, kritisches Denken und die Fähigkeit zur Qualitätssicherung steigen. SAP sollte diese Verschiebung weiterhin aktiv kommunizieren und in der internen Karriere- und Rollenentwicklung noch stärker verankern. Mitarbeitende sollten verstehen, dass KI keine Bedrohung für ihre Tätigkeit darstellt, sondern eine Erweiterung, die jedoch neue Kompetenzen erfordert. Gleichzeitig sollten Führungskräfte sensibilisiert werden, die wachsende Spreizung zwischen KI-affinen und KI-ablehnenden Mitarbeitenden frühzeitig zu erkennen und durch gezielte Unterstützungsangebote zu adressieren, bevor daraus dauerhafte Kompetenzlücken oder Teamkonflikte entstehen.
