// ---- Abbreviations ---- //
// Each entry: ("SHORT", "Full description")
#let abbreviations = (
  ("ABAP",    "Advanced Business Application Programming"),
  ("AI",      "Artificial Intelligence"),
  ("BCG",     "Boston Consulting Group"),
  ("CEO",     "Chief Executive Officer"),
  ("DHBW",    "Duale Hochschule Baden-Württemberg"),
  ("EKX",     "Enterprise Knowledge Experience"),
  ("ERP",     "Enterprise Resource Planning"),
  ("GenAI",   "Generative Artificial Intelligence"),
  ("HANA",    "High-performance ANalytic Appliance"),
  ("KI",      "Künstliche Intelligenz"),
  ("KPI",     "Key Performance Indicator"),
  ("LLM",     "Large Language Model"),
  ("LLMOps",  "Large Language Model Operations"),
  ("ML",      "Machine Learning"),
  ("MS",      "Microsoft"),
  ("PCG",     "Productivity Consulting Group"),
  ("PII",     "Personally Identifiable Information"),
  ("PM",      "Projektmanagement"),
  ("PwC",     "PricewaterhouseCoopers"),
  ("SAP",     "Systeme, Anwendungen und Produkte in der Datenverarbeitung"),
  ("UI",      "User Interface"),
  ("UI5",     "User Interface 5"),
  ("US",      "United States"),
  ("USA",     "United States of America"),
)
